### ISSUE TITLE
404 Page | 404 errors causing DB connection hang.

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#1046]
I don't even know why this happens; however, here's the deal.
It seems like missing assets or any sort of 404 error will leave a hanging DB connection associated with that request:
This happens on `dev`, `uat` and etc.

## First Log is the 404 errors currently caused by missing fonts
```
[certification.cf.uat.ds.va.gov] [172.30.66.71] [2017-02-28 21:00:19 -0500] [CASEFLOW1 ] Started GET "/assets/uswds/sourcesanspro-bold-webfont.eot" for 172.30.66.129 at 2017-02-28 21:00:19 -0500
[certification.cf.uat.ds.va.gov] [172.30.66.71] [2017-02-28 21:00:19 -0500] [CASEFLOW1 ] ** [Raven] User excluded error: #<ActionController::RoutingError: No route matches [GET] "/assets/uswds/sourcesanspro-bold-webfont.eot">
[certification.cf.uat.ds.va.gov] [172.30.66.71] [2017-02-28 21:00:19 -0500] [CASEFLOW1 ] 
ActionController::RoutingError (No route matches [GET] "/assets/uswds/sourcesanspro-bold-webfont.eot"):
  app/middleware/metrics_auth.rb:10:in `call'

[certification.cf.uat.ds.va.gov] [172.30.66.71] [2017-02-28 21:00:19 -0500] [CASEFLOW1 ] Processing by ErrorsController#show as */*
[certification.cf.uat.ds.va.gov] [172.30.66.71] [2017-02-28 21:00:19 -0500] [CASEFLOW1 ]   Parameters: {"status_code"=>"404"}
[certification.cf.uat.ds.va.gov] [172.30.66.71] [2017-02-28 21:00:19 -0500] [CASEFLOW1 ]   [1m[36mUser Load (0.7ms)[0m  [1mSELECT  "users".* FROM "users" WHERE "users"."css_id" = $1 AND "users"."station_id" = $2 LIMIT 1[0m  [["css_id", "CASEFLOW1"], ["station_id", "283"]]
[certification.cf.uat.ds.va.gov] [172.30.66.71] [2017-02-28 21:00:19 -0500] [CASEFLOW1 ]   [1m[35m (0.4ms)[0m  BEGIN
[certification.cf.uat.ds.va.gov] [172.30.66.71] [2017-02-28 21:00:19 -0500] [CASEFLOW1 ]   [1m[36m (0.5ms)[0m  [1mCOMMIT[0m
[certification.cf.uat.ds.va.gov] [172.30.66.71] [2017-02-28 21:00:19 -0500] [CASEFLOW1 ]   Rendered errors/404.html.erb within layouts/application (0.1ms)
[certification.cf.uat.ds.va.gov] [172.30.66.71] [2017-02-28 21:00:19 -0500] [CASEFLOW1 ] Completed 404 Not Found in 12ms (Views: 2.6ms | ActiveRecord: 2.1ms)
source=rack-timeout id=8a6928998ffc741d11a8c192617ee436 timeout=55000ms service=16ms state=completed
172.30.69.231 - - [28/Feb/2017:21:00:19 -0500] "GET /404 HTTP/1.1" 404 - 0.0169
source=rack-timeout id=929e9fe2d779ae37c1ef3cee5810482d timeout=55000ms state=ready
[certification.cf.uat.ds.va.gov] [172.30.66.71] [2017-02-28 21:00:20 -0500] [CASEFLOW1 ] Started GET "/assets/uswds/sourcesanspro-bold-webfont.woff" for 172.30.66.129 at 2017-02-28 21:00:20 -0500
source=rack-timeout id=929e9fe2d779ae37c1ef3cee5810482d timeout=55000ms service=1ms state=active
[certification.cf.uat.ds.va.gov] [172.30.66.71] [2017-02-28 21:00:20 -0500] [CASEFLOW1 ] ** [Raven] User excluded error: #<ActionController::RoutingError: No route matches [GET] "/assets/uswds/sourcesanspro-bold-webfont.woff">
[certification.cf.uat.ds.va.gov] [172.30.66.71] [2017-02-28 21:00:20 -0500] [CASEFLOW1 ] 
ActionController::RoutingError (No route matches [GET] "/assets/uswds/sourcesanspro-bold-webfont.woff"):
  app/middleware/metrics_auth.rb:10:in `call'

[certification.cf.uat.ds.va.gov] [172.30.66.71] [2017-02-28 21:00:20 -0500] [CASEFLOW1 ] Processing by ErrorsController#show as */*
[certification.cf.uat.ds.va.gov] [172.30.66.71] [2017-02-28 21:00:20 -0500] [CASEFLOW1 ]   Parameters: {"status_code"=>"404"}
[certification.cf.uat.ds.va.gov] [172.30.66.71] [2017-02-28 21:00:20 -0500] [CASEFLOW1 ]   [1m[35mUser Load (0.7ms)[0m  SELECT  "users".* FROM "users" WHERE "users"."css_id" = $1 AND "users"."station_id" = $2 LIMIT 1  [["css_id", "CASEFLOW1"], ["station_id", "283"]]
[certification.cf.uat.ds.va.gov] [172.30.66.71] [2017-02-28 21:00:20 -0500] [CASEFLOW1 ]   [1m[36m (0.5ms)[0m  [1mBEGIN[0m
[certification.cf.uat.ds.va.gov] [172.30.66.71] [2017-02-28 21:00:20 -0500] [CASEFLOW1 ]   [1m[35m (0.5ms)[0m  COMMIT
[certification.cf.uat.ds.va.gov] [172.30.66.71] [2017-02-28 21:00:20 -0500] [CASEFLOW1 ]   Rendered errors/404.html.erb within layouts/application (0.1ms)
[certification.cf.uat.ds.va.gov] [172.30.66.71] [2017-02-28 21:00:20 -0500] [CASEFLOW1 ] Completed 404 Not Found in 10ms (Views: 2.3ms | ActiveRecord: 2.3ms)
source=rack-timeout id=929e9fe2d779ae37c1ef3cee5810482d timeout=55000ms service=14ms state=completed
172.30.69.231 - - [28/Feb/2017:21:00:20 -0500] "GET /404 HTTP/1.1" 404 - 0.0149
source=rack-timeout id=5c46cfdf80e294c06e389831e18b71d7 timeout=55000ms state=ready
[certification.cf.uat.ds.va.gov] [172.30.66.71] [2017-02-28 21:00:20 -0500] [CASEFLOW1 ] Started GET "/assets/uswds/sourcesanspro-regular-webfont.ttf" for 172.30.66.129 at 2017-02-28 21:00:20 -0500
source=rack-timeout id=5c46cfdf80e294c06e389831e18b71d7 timeout=55000ms service=1ms state=active
source=rack-timeout id=d4073ab97ea58e284da823b02764d816 timeout=55000ms state=ready
source=rack-timeout id=d4073ab97ea58e284da823b02764d816 timeout=55000ms service=0ms state=active
[certification.cf.uat.ds.va.gov] [172.30.66.71] [2017-02-28 21:00:21 -0500] [CASEFLOW1 ] Started GET "/assets/uswds/merriweather-bold-webfont.eot" for 172.30.66.129 at 2017-02-28 21:00:21 -0500
source=rack-timeout id=5c46cfdf80e294c06e389831e18b71d7 timeout=55000ms service=1000ms state=active
172.30.69.231 - - [28/Feb/2017:21:00:21 -0500] "GET %2Fassets%2Farrow-down-36903506f59f497d5dd192a5030f53e47a9de2159d96c6dcce7ea4c6e6c137a2.svg HTTP/1.1" 200 403 0.0008
```

## Second log, resulting 500 error:
```
ActiveRecord::ConnectionTimeoutError (could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)):
  app/middleware/metrics_auth.rb:10:in `call'

[certification.cf.uat.ds.va.gov] [172.30.66.71] [2017-02-28 21:00:41 -0500] [CASEFLOW1 ] Processing by ErrorsController#show as */*
[certification.cf.uat.ds.va.gov] [172.30.66.71] [2017-02-28 21:00:41 -0500] [CASEFLOW1 ]   Parameters: {"status_code"=>"500"}
[certification.cf.uat.ds.va.gov] [172.30.66.71] [2017-02-28 21:00:41 -0500] [CASEFLOW1 ]   Rendered errors/500.html.erb within layouts/application (0.1ms)
[certification.cf.uat.ds.va.gov] [172.30.66.71] [2017-02-28 21:00:41 -0500] [CASEFLOW1 ] Completed 500 Internal Server Error in 3ms (Views: 1.2ms | ActiveRecord: 0.0ms)
source=rack-timeout id=bb300f5ce6f4842c0e4d75d6073af58c timeout=55000ms service=8976ms state=completed
172.30.69.231 - - [28/Feb/2017:21:00:50 -0500] "GET /500 HTTP/1.1" 500 - 8.9768
Warning: NLS_LANG is not set. fallback to US7ASCII.
Puma starting in single mode...
* Version 2.16.0 (ruby 2.2.4-p230), codename: Midwinter Nights Trance
* Min threads: 64, max threads: 240
* Environment: development
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/rb-readline-0.5.3/lib/readline.rb:458: warning: already initialized constant Readline::HISTORY
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/rb-readline-0.5.3/lib/readline.rb:486: warning: already initialized constant Readline::FILENAME_COMPLETION_PROC
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/rb-readline-0.5.3/lib/readline.rb:517: warning: already initialized constant Readline::USERNAME_COMPLETION_PROC
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/rb-readline-0.5.3/lib/readline.rb:523: warning: already initialized constant Readline::VERSION
I, [2017-02-28T21:00:40.668418 #2654]  INFO -- sentry: ** [Raven] Raven 1.2.3 ready to catch errors
Sidekiq client with redis options {:url=>"redis://dsva-csflow-uat.eqe4uk.0001.usgw1.cache.amazonaws.com:6379"}
creating 2 initial connections...
taking connection 1; db pool size: 1
taking connection 0; db pool size: 2
returning connection 0
returning connection 1
```

The connection is eventually restored, but you pretty much lose the whole app every 5 seconds.

# Steps

1. Cause a 404 error (right now it's caused by a wonk `uswds` gem that is missing fonts)

1. Cause a few more 404 errors (currently can be done by refreshing the page)

1. Observe that after a few 404 errors the server throws a 500 error.

1. ???

1. Profit.

# Screenshot:

Me simply refreshing 404 page.

![screenshot_2017-02-28_21-06-12](https://cloud.githubusercontent.com/assets/18075411/23443071/671ed7a8-fdfa-11e6-975d-e1b8cf2d9a74.png)

**Comment by kierachell** [comment]
Yes about 30 sec later

**Comment by askldjd** [comment]
By tracing inside the Rails DB connection pool, I can confirm that on error 404, the database connection _could_ be retrieved and never released. It doesn't _seem_ to happen every time, but when it does happens, we lose a DB connection.

When the .woff files were missing, you can hang the demo env by refreshing the home page 3-4 times. I artificially created a few fake .woff files in the EC2's assets folder, and the hang went away.

We knew from before that the Rack::Static middleware will defer to the next middleware instead of returning 404. I have seen [similar issues](https://github.com/rack/rack/issues/619) online, but the solution is unclear to me.

**Comment by shanear** [comment]
@askldjd have we been working on this? What is the status of this?

**Comment by kierachell** [comment]
**PASSED**

fixed by a nginx server
