### ISSUE TITLE
Existing EP | Can't assign existing EP and no error is logged.

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#1244]
<img width="1250" alt="screen shot 2017-03-20 at 3 14 46 pm" src="https://cloud.githubusercontent.com/assets/18075411/24117683/92519f1e-0d81-11e7-9f8d-6a7f1aaa9c7d.png">

<img width="1095" alt="screen shot 2017-03-20 at 3 30 50 pm" src="https://cloud.githubusercontent.com/assets/18075411/24117917/575d28b4-0d82-11e7-82b3-ea1ab78983df.png">

There's no error log of any kind so this is the best you gonna get. And it's not a `test data problem`.

**Comment by kierachell** [comment]
Best I could get was this and I don't even think it's related:
```
[certification.cf.uat.ds.va.gov] [172.30.66.212] [2017-03-20 19:25:39 -0400] [CASEFLOW1 ]   [1m[35mAppeal Load (0.6ms)[0m  SELECT  "appeals".* FROM "appeals" WHERE "appeals"."id" = $1 LIMIT 1  [["id", 402]]
[certification.cf.uat.ds.va.gov] [172.30.66.212] [2017-03-20 19:25:39 -0400] [CASEFLOW1 ]   [1m[36m (0.5ms)[0m  [1mSAVEPOINT active_record_1[0m
[certification.cf.uat.ds.va.gov] [172.30.66.212] [2017-03-20 19:25:39 -0400] [CASEFLOW1 ]   [1m[35mSQL (0.8ms)[0m  UPDATE "tasks" SET "outgoing_reference_id" = '600097762', "updated_at" = '2017-03-20 23:25:39.872185', "lock_version" = 6 WHERE "tasks"."type" IN ('EstablishClaim') AND "tasks"."id" = $1 AND "tasks"."lock_version" = $2  [["id", 1152], ["lock_version", 5]]
[certification.cf.uat.ds.va.gov] [172.30.66.212] [2017-03-20 19:25:39 -0400] [CASEFLOW1 ]   [1m[36mSQL (0.7ms)[0m  [1mUPDATE "tasks" SET "aasm_state" = 'reviewed', "updated_at" = '2017-03-20 23:25:39.875130', "lock_version" = 7 WHERE "tasks"."type" IN ('EstablishClaim') AND "tasks"."id" = $1 AND "tasks"."lock_version" = $2[0m  [["id", 1152], ["lock_version", 6]]
[certification.cf.uat.ds.va.gov] [172.30.66.212] [2017-03-20 19:25:39 -0400] [CASEFLOW1 ]   [1m[35m (0.5ms)[0m  RELEASE SAVEPOINT active_record_1
[certification.cf.uat.ds.va.gov] [172.30.66.212] [2017-03-20 19:25:39 -0400] [CASEFLOW1 ]   [1m[36m (0.4ms)[0m  [1mSAVEPOINT active_record_1[0m
[certification.cf.uat.ds.va.gov] [172.30.66.212] [2017-03-20 19:25:39 -0400] [CASEFLOW1 ]   [1m[35mSQL (0.5ms)[0m  UPDATE "tasks" SET "completed_at" = '2017-03-20 23:25:39.878660', "completion_status" = 4, "updated_at" = '2017-03-20 23:25:39.878984', "lock_version" = 8 WHERE "tasks"."type" IN ('EstablishClaim') AND "tasks"."id" = $1 AND "tasks"."lock_version" = $2  [["id", 1152], ["lock_version", 7]]
[certification.cf.uat.ds.va.gov] [172.30.66.212] [2017-03-20 19:25:39 -0400] [CASEFLOW1 ]   [1m[36mSQL (0.6ms)[0m  [1mUPDATE "tasks" SET "aasm_state" = 'completed', "updated_at" = '2017-03-20 23:25:39.881106', "lock_version" = 9 WHERE "tasks"."type" IN ('EstablishClaim') AND "tasks"."id" = $1 AND "tasks"."lock_version" = $2[0m  [["id", 1152], ["lock_version", 8]]
[certification.cf.uat.ds.va.gov] [172.30.66.212] [2017-03-20 19:25:39 -0400] [CASEFLOW1 ]   [1m[35m (0.4ms)[0m  RELEASE SAVEPOINT active_record_1
[certification.cf.uat.ds.va.gov] [172.30.66.212] [2017-03-20 19:25:39 -0400] [CASEFLOW1 ]   [1m[36m (0.5ms)[0m  [1mROLLBACK[0m
[certification.cf.uat.ds.va.gov] [172.30.66.212] [2017-03-20 19:25:39 -0400] [CASEFLOW1 ] Completed 500 Internal Server Error in 24ms (ActiveRecord: 8.1ms)
[certification.cf.uat.ds.va.gov] [172.30.66.212] [2017-03-20 19:25:39 -0400] [CASEFLOW1 ] ** [Raven] Sending event d889e6971d88f32e0581cf32ae73d177 to Sentry
[certification.cf.uat.ds.va.gov] [172.30.66.212] [2017-03-20 19:25:39 -0400] [CASEFLOW1 ] 
NoMethodError (undefined method `full_grant?' for #<Hash:0x007f7150753e38>):
  app/services/appeal_repository.rb:208:in `location_after_dispatch'
  app/services/appeal_repository.rb:201:in `update_location_after_dispatch!'
  app/services/dispatch.rb:81:in `block in assign_existing_end_product!'
  app/services/dispatch.rb:78:in `assign_existing_end_product!'
  app/controllers/establish_claims_controller.rb:39:in `assign_existing_end_product'
  app/middleware/metrics_collector.rb:14:in `call'
  app/middleware/metrics_auth.rb:10:in `call'
```

**Comment by shanear** [comment]
this is a dup of https://github.com/department-of-veterans-affairs/caseflow/issues/1254

**Comment by kierachell** [comment]
or #1254 is a dup of this ;)
