### ISSUE TITLE
[Sentry] ArgumentError: bad value for range in AdvanceOnDocketMotion

### ISSUE THREAD

**Issue by jcq** [department-of-veterans-affairs/caseflow#12896]
## Description
It looks like there is an invalid date range error for this query:
```
def granted_for_person?(person_id, appeal_receipt_date)
      where(
        granted: true,
        created_at: appeal_receipt_date..DateTime::Infinity.new,
        person_id: person_id
      ).any?
end
```
Perhaps this indicates a problem with (an invalid) `appeal_receipt_date`?

## Background/context/resources
- [Sentry Alert](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7534/)

**Comment by yoomlam** [comment]
```
ArgumentError: bad value for range
  from app/models/advance_on_docket_motion.rb:22:in `granted_for_person?'
  from app/models/person.rb:13:in `advanced_on_docket?'
  from app/models/claimant.rb:42:in `advanced_on_docket?'
  from app/models/appeal.rb:243:in `advanced_on_docket?'
  from fast_jsonapi/attribute.rb:14:in `serialize'
  from fast_jsonapi/serialization_core.rb:48:in `block in attributes_hash'
  from fast_jsonapi/serialization_core.rb:47:in `each'
  from fast_jsonapi/serialization_core.rb:47:in `each_with_object'
  from fast_jsonapi/serialization_core.rb:47:in `attributes_hash'
  from fast_jsonapi/serialization_core.rb:80:in `record_hash'
  from fast_jsonapi/object_serializer.rb:58:in `block in hash_for_collection'
  from fast_jsonapi/object_serializer.rb:57:in `each'
  from fast_jsonapi/object_serializer.rb:57:in `hash_for_collection'
  from fast_jsonapi/object_serializer.rb:33:in `serializable_hash'
  from app/workflows/case_search_results_base.rb:54:in `json_appeals'
  from app/workflows/case_search_results_base.rb:87:in `search_results'
  from app/workflows/case_search_results_base.rb:15:in `call'
  from app/controllers/appeals_controller.rb:29:in `block (2 levels) in index'
```

**Comment by lomky** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | ||||
3 | ||||||||
5 | 
8 | 
```

Do we expect `appeal_receipt_date` to have system-reasonable entries? Some 'dates' in caseflow are based on form info, not system-dates.

These fields are nullable. Should they be? Look into that. Get a count of null values for this field in prod? 


#### Why 2?
* Could be a simple fix based on the answers to the questions.


#### Why 3?
* Investigation, determining desired behavior (nullable?), implement solution and tests.
* possible weird prod data to fix
