### ISSUE TITLE
NoMethodError in FetchDocumentsForReaderUserJob

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#13339]
##  Description

Seeing this error:

```
NoMethodError

undefined method `[]' for nil:NilClass
```

in `FetchDocumentsForReaderUserJob`. It appears to be an error from the VBMS client (?)

## Background/context/resources

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/8110/events/24b7a58b24fd48c8aa687e70f4510c62/

## Technical notes

N/A

**Comment by yoomlam** [comment]
```
NoMethodError: undefined method `[]' for nil:NilClass
  from vbms/service/paged_documents.rb:16:in `call'
  from app/services/external_api/vbms_service.rb:206:in `block in call_and_log_service'
  from app/services/metrics_service.rb:14:in `block in record'
  from benchmark.rb:293:in `measure'
  from app/services/metrics_service.rb:13:in `record'
  from app/services/external_api/vbms_service.rb:203:in `call_and_log_service'
  from app/services/external_api/vbms_documents_for_appeal.rb:48:in `fetch_veteran_file_number_docs'
  from app/services/external_api/vbms_documents_for_appeal.rb:14:in `fetch'
  from app/services/external_api/vbms_service.rb:34:in `fetch_documents_for'
  from app/services/document_fetcher.rb:81:in `fetch_documents_from_service!'
  from app/services/document_fetcher.rb:10:in `initialize'
  from app/models/legacy_appeal.rb:167:in `new'
  from app/models/legacy_appeal.rb:167:in `document_fetcher'
  from app/workflows/fetch_documents_for_reader_job.rb:32:in `fetch_for_appeal'
  from app/workflows/fetch_documents_for_reader_job.rb:12:in `block in process'
  from app/workflows/fetch_documents_for_reader_job.rb:12:in `each'
  from app/workflows/fetch_documents_for_reader_job.rb:12:in `process'
```

**Comment by yoomlam** [comment]
Standard Sentry estimate of 3.
