### ISSUE TITLE
[Flaky Test] HLR Intake edit

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#13630]
## Background/context/resources

```
$ CI=true bundle exec rspec ./spec/feature/intake/higher_level_review/edit_spec.rb[1:2:1:1,1:2:2,1:3:1]  --seed 23816
Run options: include {:focus=>true, :ids=>{"./spec/feature/intake/higher_level_review/edit_spec.rb"=>["1:2:1:1", "1:2:2", "1:3:1"]}}

Randomized with seed 23816

Higher Level Review Edit issues
  when there are ineligible issues

All visited screens will be scanned for 508 accessibility compliance.

1st Try error in ./spec/feature/intake/higher_level_review/edit_spec.rb:329:
expected to find css "label" at least 1 time but there were no matches

RSpec::Retry: 2nd try ./spec/feature/intake/higher_level_review/edit_spec.rb:329
    re-applies eligibility check on remove/re-add of ineligible issue (FAILED - 1)
  HTML screenshot: /Users/pkarman/va-appeals/caseflow/tmp/capybara/screenshot_2020-03-05-15-54-33.036.html
  Image screenshot: /Users/pkarman/va-appeals/caseflow/tmp/capybara/screenshot_2020-03-05-15-54-33.036.png
    VACOLS issue from before AMA opted in

1st Try error in ./spec/feature/intake/higher_level_review/edit_spec.rb:299:
expected to find text "Left knee granted is ineligible because it was last processed as a Higher-Level Review and this can't be done twice in a row" in ""

RSpec::Retry: 2nd try ./spec/feature/intake/higher_level_review/edit_spec.rb:299
      shows the Higher-Level Review Edit page with ineligibility messages (FAILED - 2)
  HTML screenshot: /Users/pkarman/va-appeals/caseflow/tmp/capybara/screenshot_2020-03-05-15-54-50.113.html
  Image screenshot: /Users/pkarman/va-appeals/caseflow/tmp/capybara/screenshot_2020-03-05-15-54-50.113.png
  Nonrating issue with untimely date and VACOLS opt-in

1st Try error in ./spec/feature/intake/higher_level_review/edit_spec.rb:448:
expected to find button "Next" but there were no matches

RSpec::Retry: 2nd try ./spec/feature/intake/higher_level_review/edit_spec.rb:448
    does not apply untimely check to legacy opt-in (FAILED - 3)
  HTML screenshot: /Users/pkarman/va-appeals/caseflow/tmp/capybara/screenshot_2020-03-05-15-55-06.834.html
  Image screenshot: /Users/pkarman/va-appeals/caseflow/tmp/capybara/screenshot_2020-03-05-15-55-06.834.png

Failures:

  1) Higher Level Review Edit issues when there are ineligible issues re-applies eligibility check on remove/re-add of ineligible issue
     Failure/Error: find_all("label", text: description, minimum: 1).first.click

     Capybara::ExpectationNotMet:
       expected to find css "label" at least 1 time but there were no matches
     # ./spec/support/intake_helpers.rb:205:in `add_intake_rating_issue'
     # ./spec/feature/intake/higher_level_review/edit_spec.rb:352:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:23:in `block (2 levels) in <top (required)>'

  2) Higher Level Review Edit issues when there are ineligible issues VACOLS issue from before AMA opted in shows the Higher-Level Review Edit page with ineligibility messages
     Failure/Error:
       expect(page).to have_content(
         "#{ri_with_previous_hlr.contention_text} #{ineligible.higher_level_review_to_higher_level_review}"
       )

       expected to find text "Left knee granted is ineligible because it was last processed as a Higher-Level Review and this can't be done twice in a row" in ""
     # ./spec/feature/intake/higher_level_review/edit_spec.rb:301:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:23:in `block (2 levels) in <top (required)>'

  3) Higher Level Review Edit issues Nonrating issue with untimely date and VACOLS opt-in does not apply untimely check to legacy opt-in
     Failure/Error: expect(page).to have_button(add_button_text, disabled: true)
       expected to find button "Next" but there were no matches
     # ./spec/support/intake_helpers.rb:228:in `add_intake_nonrating_issue'
     # ./spec/feature/intake/higher_level_review/edit_spec.rb:453:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:23:in `block (2 levels) in <top (required)>'

Finished in 1 minute 8.5 seconds (files took 6.41 seconds to load)
3 examples, 3 failures

Failed examples:

rspec ./spec/feature/intake/higher_level_review/edit_spec.rb:329 # Higher Level Review Edit issues when there are ineligible issues re-applies eligibility check on remove/re-add of ineligible issue
rspec ./spec/feature/intake/higher_level_review/edit_spec.rb:299 # Higher Level Review Edit issues when there are ineligible issues VACOLS issue from before AMA opted in shows the Higher-Level Review Edit page with ineligibility messages
rspec ./spec/feature/intake/higher_level_review/edit_spec.rb:448 # Higher Level Review Edit issues Nonrating issue with untimely date and VACOLS opt-in does not apply untimely check to legacy opt-in

Randomized with seed 23816
```
 - Has the test already been skipped in the code?
   - [ ] Skipped
   - [x] Not Skipped
 - Related Flakes
    + 

## Approach

Time box this investigation and fix.

Remember that if a test has been skipped for a decent amount of time, it may no longer map to the exact code.

If you reach the end of your time box and don't feel like the solution is in sight:
  - [ ] document the work you've done, including dead ends and research
  - [ ] skip the test in the code
  - [ ] file a follow on ticket
  - [ ] close this issue

**Comment by pkarman** [comment]
this was not a flake but local fail. #13636 should resolve.
