### ISSUE TITLE
Create PropTypes for all Components

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1442]
We're sadly missing PropTypes so far. It's a widely accepted best practice. Let's go through and add PropTypes for all the tickets.

**Comment by NickHeiner** [comment]
Have we considered using something like Flow or Typescript instead?

**Comment by aroltsch** [comment]
@amprokop ^^

**Comment by amprokop** [comment]
We haven't seriously considered either option although folks chatter about them from time to time. We should make a discussion issue to talk about it! 

For now, I think we should continue using PropTypes though, as it accomplishes (some of) the same thing and adding a new tool entirely, propagating that info to the team, training everyone up, etc will be much more involved.

Thoughts, @NickHeiner @aroltsch?

**Comment by aroltsch** [comment]
I have very limited knowledge about ReactJS so I will go with whatever is decided.

**Comment by NickHeiner** [comment]
PropTypes are definitely less involved than Flow or TypeScript. I'm fine sticking with that for now.

**Comment by kierachell** [comment]
Date picker seems to go crazy:
https://github.com/department-of-veterans-affairs/caseflow/blob/9a7090cad781c56435a8bbc010d51f9f78fbd200/client/app/certification/SignAndCertify.jsx#L72

```
Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.r.dateFill [as onChange] (https://certification.cf.preprod.ds.va.gov/assets/application-83ba7b609b0b80ff1a6bcb24b81e51d274547014e3d0a058370cf3afa8048df1.js:6:32438)
    at r.onChange (https://certification.cf.preprod.ds.va.gov/assets/application-83ba7b609b0b80ff1a6bcb24b81e51d274547014e3d0a058370cf3afa8048df1.js:2:4238)
    at Object.executeOnChange (https://certification.cf.preprod.ds.va.gov/assets/application-83ba7b609b0b80ff1a6bcb24b81e51d274547014e3d0a058370cf3afa8048df1.js:7:24792)
    at h.o (https://certification.cf.preprod.ds.va.gov/assets/application-83ba7b609b0b80ff1a6bcb24b81e51d274547014e3d0a058370cf3afa8048df1.js:27:12257)
    at Object.t (https://certification.cf.preprod.ds.va.gov/assets/application-83ba7b609b0b80ff1a6bcb24b81e51d274547014e3d0a058370cf3afa8048df1.js:7:25161)
    at a (https://certification.cf.preprod.ds.va.gov/assets/application-83ba7b609b0b80ff1a6bcb24b81e51d274547014e3d0a058370cf3afa8048df1.js:7:21260)
    at Object.s [as executeDispatchesInOrder] (https://certification.cf.preprod.ds.va.gov/assets/application-83ba7b609b0b80ff1a6bcb24b81e51d274547014e3d0a058370cf3afa8048df1.js:7:21475)
    at p (https://certification.cf.preprod.ds.va.gov/assets/application-83ba7b609b0b80ff1a6bcb24b81e51d274547014e3d0a058370cf3afa8048df1.js:5:17812)
    at m (https://certification.cf.preprod.ds.va.gov/assets/application-83ba7b609b0b80ff1a6bcb24b81e51d274547014e3d0a058370cf3afa8048df1.js:5:17938)
    at Array.forEach (native)
```
<img width="1372" alt="screen shot 2017-04-17 at 12 59 29 pm" src="https://cloud.githubusercontent.com/assets/18075411/25096446/40b0df50-236e-11e7-8997-1216b286e54c.png">

**Comment by aroltsch** [comment]
@kierachell this is a separate issue. It existed before my changes.
