### ISSUE TITLE
[Flaky Test] Appeal Edit issues allows adding/removing issues

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#14477]
## Description

```
Appeal Edit issues allows adding/removing issues - spec.feature.intake.appeal.edit_spec
spec/feature/intake/appeal/edit_spec.rb
Failure/Error: expect(page).to have_content("2. #{nonrating_request_issue.description}")
  expected to find text "2. Military Retired Pay - nonrating description" in "CaseflowIntake\n  |   Merica, Ed (100000019)\nDSUSER (DSUSER)\nEdit Issues\nEstablished Invalid date by DSUSER\nVeteran Ed Merica (100000019)\nNOD receipt date 05/16/2020\nReview option Evidence Submission\nClaimant Ed Merica\nRequested issues\n1. Military Retired Pay - nonrating description\nDecision date: 05/05/2020\nSelect action\nWithdraw issue\nRemove issue\n2. PTSD denied\nDecision date: 05/16/2020\nSelect action\nWithdraw issue\nRemove issue\n+ Add issue\nCancelSave\n2 issues\nBuilt with ♡ by the Digital Service at VA\nTrack Caseflow Status|Send feedback"
./spec/feature/intake/appeal/edit_spec.rb:80:in `block (2 levels) in <top (required)>'
./spec/spec_helper.rb:23:in `block (2 levels) in <top (required)>'
```

Note: It's looking for `2. Military Retired Pay - nonrating description`. The actual seems to have it mislabeled or in a different order: `1. Military Retired Pay - nonrating description`.

## Background/context/resources

 - Circle CI Error:  [Appeal Edit issues allows adding/removing issues - spec.feature.intake.appeal.edit_spec](https://app.circleci.com/pipelines/github/department-of-veterans-affairs/caseflow/32139/workflows/6c7438b3-3910-4cb9-a743-8d88d722a5f5/jobs/117811/tests)
 - Has the test already been skipped in the code?
   - [ ] Skipped
   - [x] Not Skipped
 - Related Flakes
    + 

## Approach

Time box this investigation and fix.

Remember that if a test has been skipped for a decent amount of time, it may no longer map to the exact code.

If you reach the end of your time box and don't feel like the solution is in sight:
  - [ ] document the work you've done, including dead ends and research
  - [ ] skip the test in the code
  - [ ] file a follow on ticket
  - [ ] close this issue

**Comment by pkarman** [comment]
again https://app.circleci.com/pipelines/github/department-of-veterans-affairs/caseflow/32177/workflows/a9589b51-e7cf-4889-8fb5-04b647751fc5/jobs/117960/parallel-runs/2?filterBy=FAILED
