### ISSUE TITLE
Setup docs may be incorrect

### ISSUE THREAD

**Issue by NickHeiner** [department-of-veterans-affairs/caseflow#1483]
I am trying to follow the setup docs and I got the following error:

```
λ rake db:setup
rake aborted!
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "documents" does not exist
LINE 5:                WHERE a.attrelid = '"documents"'::regclass
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"documents"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
/Users/nickheiner/Code/caseflow-2/app/models/document.rb:48:in `from_vbms_document'
/Users/nickheiner/Code/caseflow-2/lib/fakes/appeal_repository.rb:364:in `nod_document'
/Users/nickheiner/Code/caseflow-2/lib/fakes/appeal_repository.rb:168:in `appeal_ready_to_certify'
/Users/nickheiner/Code/caseflow-2/lib/fakes/appeal_repository.rb:438:in `seed!'
/Users/nickheiner/Code/caseflow-2/lib/fakes/initializer.rb:18:in `development!'
/Users/nickheiner/Code/caseflow-2/config/initializers/fake_dependencies.rb:1:in `<top (required)>'
/Users/nickheiner/Code/caseflow-2/config/environment.rb:5:in `<top (required)>'
PG::UndefinedTable: ERROR:  relation "documents" does not exist
LINE 5:                WHERE a.attrelid = '"documents"'::regclass
                                          ^
/Users/nickheiner/Code/caseflow-2/app/models/document.rb:48:in `from_vbms_document'
/Users/nickheiner/Code/caseflow-2/lib/fakes/appeal_repository.rb:364:in `nod_document'
/Users/nickheiner/Code/caseflow-2/lib/fakes/appeal_repository.rb:168:in `appeal_ready_to_certify'
/Users/nickheiner/Code/caseflow-2/lib/fakes/appeal_repository.rb:438:in `seed!'
/Users/nickheiner/Code/caseflow-2/lib/fakes/initializer.rb:18:in `development!'
/Users/nickheiner/Code/caseflow-2/config/initializers/fake_dependencies.rb:1:in `<top (required)>'
/Users/nickheiner/Code/caseflow-2/config/environment.rb:5:in `<top (required)>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => environment
(See full trace by running task with --trace)
```

If I examine what exists in Postgres, I see two databases:

```
λ psql -l | grep caseflow
 caseflow_certification_development | nickheiner | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 caseflow_certification_test        | nickheiner | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
```

But neither have any tables:

```
λ psql caseflow_certification_test
psql (9.6.2)
Type "help" for help.

caseflow_certification_test=# \dt
No relations found.
caseflow_certification_test=# \q
λ psql caseflow_certification_development
psql (9.6.2)
Type "help" for help.

caseflow_certification_development=# \dt
No relations found.
caseflow_certification_development=# \q
```

When I was hacking around earlier, I actually saw a schema in `_test` but not in `_development`. Now I don't see one in either. I am not sure what I did to cause that difference. ¯\_(ツ)_/¯

I tried doing a fresh clone and repeating the instructions in a new repo but it still didn't work. I am open to the possibility that I'm screwing something up, though. :smile:

```
λ which ruby
/Users/nickheiner/.rbenv/shims/ruby
λ ruby -v
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin16]
λ which bundler
/Users/nickheiner/.rbenv/shims/bundler
λ bundler -v
Bundler version 1.14.6
λ pg_ctl -V
pg_ctl (PostgreSQL) 9.6.2
```

**Comment by NickHeiner** [comment]
There was an error with how the db was being set up, but it has since been resolved.
