### ISSUE TITLE
Migrations failing when running on a newly created db

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/caseflow#1485]
```
[teja@Tejas-MacBook caseflow (master ✗)]$ rake db:setup
rake aborted!
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "documents" does not exist
LINE 5:                WHERE a.attrelid = '"documents"'::regclass
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"documents"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
/Users/teja/git/caseflow/app/models/document.rb:48:in `from_vbms_document'
/Users/teja/git/caseflow/lib/fakes/appeal_repository.rb:364:in `nod_document'
/Users/teja/git/caseflow/lib/fakes/appeal_repository.rb:168:in `appeal_ready_to_certify'
/Users/teja/git/caseflow/lib/fakes/appeal_repository.rb:438:in `seed!'
/Users/teja/git/caseflow/lib/fakes/initializer.rb:18:in `development!'
/Users/teja/git/caseflow/config/initializers/fake_dependencies.rb:1:in `<top (required)>'
/Users/teja/git/caseflow/config/environment.rb:5:in `<top (required)>'
PG::UndefinedTable: ERROR:  relation "documents" does not exist
LINE 5:                WHERE a.attrelid = '"documents"'::regclass
                                          ^
/Users/teja/git/caseflow/app/models/document.rb:48:in `from_vbms_document'
/Users/teja/git/caseflow/lib/fakes/appeal_repository.rb:364:in `nod_document'
/Users/teja/git/caseflow/lib/fakes/appeal_repository.rb:168:in `appeal_ready_to_certify'
/Users/teja/git/caseflow/lib/fakes/appeal_repository.rb:438:in `seed!'
/Users/teja/git/caseflow/lib/fakes/initializer.rb:18:in `development!'
/Users/teja/git/caseflow/config/initializers/fake_dependencies.rb:1:in `<top (required)>'
/Users/teja/git/caseflow/config/environment.rb:5:in `<top (required)>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => environment
(See full trace by running task with --trace)
```

**Comment by tejans24** [comment]
It's seems like a problem with Document being referenced Fakes::Initializer

**Comment by tejans24** [comment]
#1494 fixed this issue
