### ISSUE TITLE
Mocha tests fail when new dep is brought in

### ISSUE THREAD

**Issue by NickHeiner** [department-of-veterans-affairs/caseflow#1530]
**Impact:**
* Blocks #1547.
* Slows dev velocity because merging `npm-shrinkwrap.json` changes is much harder
* Prevents us from making other substantial dep changes.

## Overview
There is a dependency update that breaks the mocha tests. I am not sure what it is, but if I `npm install` without the shrinkwrap file present, I'll see an error when I go to run the tests. The error also occurs if too drastic a change to the shrinkwrap file is made. 

The error:

```
> NODE_ENV=test mocha --recursive test/setup.js test/* --compilers js:babel-core/register

Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
/Users/nth/dev/caseflow/client/node_modules/pdfjs-dist/build/pdf.js:7956
  PDFJS.compatibilityChecked = true;
                             ^

TypeError: Cannot set property 'compatibilityChecked' of undefined
    at Object.<anonymous> (/Users/nth/dev/caseflow/client/node_modules/pdfjs-dist/build/pdf.js:7956:30)
    at Object.<anonymous> (/Users/nth/dev/caseflow/client/node_modules/pdfjs-dist/build/pdf.js:9351:30)
    at __w_pdfjs_require__ (/Users/nth/dev/caseflow/client/node_modules/pdfjs-dist/build/pdf.js:45:30)
    at Object.<anonymous> (/Users/nth/dev/caseflow/client/node_modules/pdfjs-dist/build/pdf.js:101:21)
    at Object.<anonymous> (/Users/nth/dev/caseflow/client/node_modules/pdfjs-dist/build/pdf.js:1208:30)
    at __w_pdfjs_require__ (/Users/nth/dev/caseflow/client/node_modules/pdfjs-dist/build/pdf.js:45:30)
    at Object.globalScope (/Users/nth/dev/caseflow/client/node_modules/pdfjs-dist/build/pdf.js:7898:23)
    at __w_pdfjs_require__ (/Users/nth/dev/caseflow/client/node_modules/pdfjs-dist/build/pdf.js:45:30)
```

Relatedly, the way we're doing mocha tests is hazardous because it uses a separate compile path from our actual app:

```json
"test": "NODE_ENV=test mocha --recursive test/setup.js test/* --compilers js:babel-core/register",
```

It uses mocha's compiler feature instead of webpack. It could be that we could just fix this issue by fixing the tests to use webpack.

I have spent some time trying to figure out why this problem was occurring, but don't have the bandwidth right now to dig in fully. It wasn't immediately obvious.

**Comment by NickHeiner** [comment]
Closing because the tests passed on CI.
