### ISSUE TITLE
VirtualHearingConversationFailed error: unknown attribute 'status'

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#15430]
## Description

We're seeing an error when converting a hearing to virtual, where the backend tries up update a field called `status`, but `status` is not actually an editable field in the database. The frontend probably should not be including this field in the request, but also, the backend could strip unknown attributes before the `update` call.

The API error was surfacing a related error on the frontend, where the error handling code was expecting a slightly different error format.

## Acceptance criteria
- [ ] Fix frontend TypeError
- [ ] Fix backend unknown attribute error
- [ ] Ensure the `VirtualHearingConversationFailed` error gets routed to `#appeals-hearings` instead of `#appeals-queue-alerts`

## Background/context/resources

Backend Sentry Alert: https://sentry.prod.appeals.va.gov/department-of-veterans-affairs/caseflow/issues/11903/
Frontend Sentry Alert: https://sentry.prod.appeals.va.gov/department-of-veterans-affairs/caseflow/issues/11904/

Backend Stack Trace:

```
ActiveModel::UnknownAttributeError: unknown attribute 'status' for VirtualHearing.
  from active_model/attribute_assignment.rb:53:in `_assign_attribute'
  from active_model/attribute_assignment.rb:44:in `block in _assign_attributes'
  from active_model/attribute_assignment.rb:43:in `each'
  from active_model/attribute_assignment.rb:43:in `_assign_attributes'
  from active_record/attribute_assignment.rb:23:in `_assign_attributes'
  from active_model/attribute_assignment.rb:35:in `assign_attributes'
  from active_record/persistence.rb:440:in `block in update!'
  from active_record/transactions.rb:387:in `block in with_transaction_returning_status'
  from active_record/connection_adapters/abstract/database_statements.rb:265:in `transaction'
  from active_record/transactions.rb:212:in `transaction'
  from active_record/transactions.rb:385:in `with_transaction_returning_status'
  from active_record/persistence.rb:439:in `update!'
  from app/models/hearings/forms/base_hearing_update_form.rb:248:in `create_or_update_virtual_hearing'
  from app/models/hearings/forms/base_hearing_update_form.rb:21:in `block in update'
  from active_record/connection_adapters/abstract/database_statements.rb:265:in `transaction'
  from active_record/transactions.rb:212:in `transaction'
  from app/models/hearings/forms/base_hearing_update_form.rb:17:in `update'
  from app/services/virtual_hearings/convert_to_virtual_hearing_service.rb:21:in `convert_hearing_to_virtual'
  from app/models/tasks/assign_hearing_disposition_task.rb:186:in `block in reschedule'
  from app/models/application_record.rb:34:in `block in multi_transaction'
  from app/models/application_record.rb:29:in `block (2 levels) in multi_transaction'
  from active_record/connection_adapters/abstract/database_statements.rb:265:in `transaction'
  from active_record/transactions.rb:212:in `transaction'
  from app/models/application_record.rb:29:in `block in multi_transaction'
  from active_record/connection_adapters/abstract/database_statements.rb:265:in `transaction'
  from active_record/transactions.rb:212:in `transaction'
  from app/models/application_record.rb:28:in `multi_transaction'
  from app/models/application_record.rb:34:in `multi_transaction'
  from app/models/tasks/assign_hearing_disposition_task.rb:177:in `reschedule'
  from app/models/tasks/assign_hearing_disposition_task.rb:225:in `reschedule_or_schedule_later'
  from app/models/tasks/assign_hearing_disposition_task.rb:217:in `block in mark_hearing_postponed'
  from app/models/application_record.rb:34:in `block in multi_transaction'
  from app/models/application_record.rb:29:in `block (2 levels) in multi_transaction'
  from active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
  from active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
  from monitor.rb:226:in `mon_synchronize'
  from active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
  from active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
  from active_record/transactions.rb:212:in `transaction'
  from app/models/application_record.rb:29:in `block in multi_transaction'
  from active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
  from active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
  from monitor.rb:226:in `mon_synchronize'
  from active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
  from active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
  from active_record/transactions.rb:212:in `transaction'
  from app/models/application_record.rb:28:in `multi_transaction'
  from app/models/application_record.rb:34:in `multi_transaction'
  from app/models/tasks/assign_hearing_disposition_task.rb:215:in `mark_hearing_postponed'
  from app/models/tasks/assign_hearing_disposition_task.rb:146:in `update_hearing_and_self'
  from app/models/tasks/assign_hearing_disposition_task.rb:72:in `update_from_params'
  from app/controllers/tasks_controller.rb:96:in `update'
  from action_controller/metal/basic_implicit_render.rb:6:in `send_action'
  from abstract_controller/base.rb:194:in `process_action'
  from ddtrace/contrib/action_pack/action_controller/instrumentation.rb:118:in `process_action'
  from action_controller/metal/rendering.rb:30:in `process_action'
  from abstract_controller/callbacks.rb:42:in `block in process_action'
  from active_support/callbacks.rb:109:in `block in run_callbacks'
  from app/controllers/application_controller.rb:227:in `set_timezone'
  from active_support/callbacks.rb:118:in `block in run_callbacks'
  from raven/integrations/rails/controller_transaction.rb:7:in `block in included'
  from active_support/callbacks.rb:118:in `instance_exec'
  from active_support/callbacks.rb:118:in `block in run_callbacks'
  from active_support/callbacks.rb:136:in `run_callbacks'
  from abstract_controller/callbacks.rb:41:in `process_action'
  from action_controller/metal/rescue.rb:22:in `process_action'
  from action_controller/metal/instrumentation.rb:34:in `block in process_action'
  from active_support/notifications.rb:168:in `block in instrument'
  from active_support/notifications/instrumenter.rb:23:in `instrument'
  from active_support/notifications.rb:168:in `instrument'
  from action_controller/metal/instrumentation.rb:32:in `process_action'
  from action_controller/metal/params_wrapper.rb:256:in `process_action'
  from active_record/railties/controller_runtime.rb:24:in `process_action'
  from abstract_controller/base.rb:134:in `process'
  from action_view/rendering.rb:32:in `process'
  from action_controller/metal.rb:191:in `dispatch'
  from action_controller/metal.rb:252:in `dispatch'
  from action_dispatch/routing/route_set.rb:52:in `dispatch'
  from action_dispatch/routing/route_set.rb:34:in `serve'
  from action_dispatch/journey/router.rb:52:in `block in serve'
  from action_dispatch/journey/router.rb:35:in `each'
  from action_dispatch/journey/router.rb:35:in `serve'
  from action_dispatch/routing/route_set.rb:840:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from new_relic/rack/agent_hooks.rb:30:in `traced_call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from new_relic/rack/browser_monitoring.rb:32:in `traced_call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from rack/tempfile_reaper.rb:15:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from rack/etag.rb:27:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from rack/conditional_get.rb:40:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from rack/head.rb:12:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from action_dispatch/http/content_security_policy.rb:18:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from rack/session/abstract/id.rb:266:in `context'
  from rack/session/abstract/id.rb:260:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from action_dispatch/middleware/cookies.rb:670:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from action_dispatch/middleware/callbacks.rb:28:in `block in call'
  from active_support/callbacks.rb:98:in `run_callbacks'
  from action_dispatch/middleware/callbacks.rb:26:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from action_dispatch/middleware/debug_exceptions.rb:61:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from ddtrace/contrib/rails/middlewares.rb:17:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from action_dispatch/middleware/show_exceptions.rb:33:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from rails/rack/logger.rb:38:in `call_app'
  from rails/rack/logger.rb:26:in `block in call'
  from active_support/tagged_logging.rb:71:in `block in tagged'
  from active_support/tagged_logging.rb:28:in `tagged'
  from active_support/tagged_logging.rb:71:in `tagged'
  from rails/rack/logger.rb:26:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from action_dispatch/middleware/remote_ip.rb:81:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from request_store/middleware.rb:19:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from action_dispatch/middleware/request_id.rb:27:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from rack/method_override.rb:24:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from rack/runtime.rb:22:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from action_dispatch/middleware/executor.rb:14:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from action_dispatch/middleware/static.rb:127:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from rack/sendfile.rb:110:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from raven/integrations/rack.rb:51:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from ddtrace/contrib/rack/middlewares.rb:85:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from action_dispatch/middleware/static.rb:127:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from rails/engine.rb:524:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
  from puma/configuration.rb:227:in `call'
  from puma/server.rb:706:in `handle_request'
  from puma/server.rb:476:in `process_client'
  from puma/server.rb:334:in `block in run'
  from puma/thread_pool.rb:135:in `block in spawn_thread'
```

Frontend Stack Trace:

```
TypeError: Cannot read property 'split' of undefined
  at parseVirtualHearingErrors(./app/hearings/utils.js:419:35)
  at call(./app/hearings/components/ScheduleVeteran.jsx:236:25)
  at tryCatch(./node_modules/regenerator-runtime/runtime.js:45:40)
  at _invoke(./node_modules/regenerator-runtime/runtime.js:274:22)
  at Generator.forEach.e.<computed> [as throw](./node_modules/regenerator-runtime/runtime.js:97:21)
  at G5e(/assets/sourcemap-webpack-bundle.js.map:166:32)
  at s(/assets/sourcemap-webpack-bundle.js.map:166:32)
```

**Comment by ferristseng** [comment]
Resolved in #15464
