### ISSUE TITLE
[Flaky Test] Intake Confirmation Page contains unexpected "Informal Conference Tracked Item"

### ISSUE THREAD

**Issue by n1zyy** [department-of-veterans-affairs/caseflow#15563]
## Description

This expectation is failing:
> Intake Confirmation Page when completing a claim review Confirmation copy HRL allows ineligible issues to remain due to untimeliness does not show tracked item if there is no End Product - spec.feature.intake.confirmation_page_spec

With:
```
Failure/Error: expect(page).to_not have_content("Informal Conference Tracked Item")
  expected not to find text "Informal Conference Tracked Item" in "CaseflowIntake\n  |   Smith, Bob (100000019)\nSearch cases\nDSUSER (DSUSER)\n1. Select Form\n2. Search\n3. Review\n4. Add Issues\n5. Confirmation\nIntake completed\nBob Smith's (ID #100000019) Request for Decision Review Request: Higher-Level Review — VA Form 20-0996 has been submitted. It may take up to 24 hours for the claim to establish.\nIf needed, you may correct the issues.\nEdit the notice letter to reflect the status of requested issues.\nA Higher-Level Review Nonrating EP is being established:\nContention: Active Duty Adjustments - Some description\nInformal Conference Tracked Item\nYou will receive a message in your Caseflow Inbox if the establishment fails or is delayed.\nBegin next intake\nBuilt with ♡ by the Digital Service at VA\nTrack Caseflow Status|Send feedback"
./spec/feature/intake/confirmation_page_spec.rb:28:in `block (5 levels) in <top (required)>'
./spec/spec_helper.rb:23:in `block (2 levels) in <top (required)>'
```

## Background/context/resources

 - Circle CI Error:  [Intake Confirmation Page when completing a claim review Confirmation copy HRL allows ineligible issues to remain due to untimeliness does not show tracked item if there is no End Product - spec.feature.intake.confirmation_page_spec](https://app.circleci.com/pipelines/github/department-of-veterans-affairs/caseflow/36343/workflows/a2ec4063-b87b-4368-b955-f9a588c0457f/jobs/135197)
 - Has the test already been skipped in the code?
   - [ ] Skipped
   - [x] Not Skipped
 - Related Flakes

## Approach

Time box this investigation and fix.

Remember that if a test has been skipped for a decent amount of time, it may no longer map to the exact code.

If you reach the end of your time box and don't feel like the solution is in sight:
  - [ ] document the work you've done, including dead ends and research
  - [ ] skip the test in the code
  - [ ] file a follow on ticket
  - [ ] close this issue

**Comment by n1zyy** [comment]
False alarm. Turns out this was fixed before I filed this but I hadn't merged it into master at the time. Closing.
