### ISSUE TITLE
Document Viewer | Side Menu component Errors

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1573]
**Story**

As an attorney who wants to label categories to documents before making a decision, I want to know  when I am unable to add or edit label(s).

## Acceptance Criteria
- Verify that an error pops up in these 3 scenarios:
   1. Request to add or edit Categories failed
   1. Request to add or delete Issue tags failed
- Verify the specs of Error lite component in mock below
- Verify that it comes up 15px above each UI component 

## Mockups

**Categories**
![image](https://cloud.githubusercontent.com/assets/13420618/25025664/1ecf9296-2071-11e7-90d8-747774c5e8e5.png)

**Issue tags**
![image](https://cloud.githubusercontent.com/assets/13420618/25025724/59fb3668-2071-11e7-9c5e-50c97295fca0.png)

Spec:
- Alert message uses the standard `Alert` component used elsewhere in the app

## Related 
#1274
#1854

**Comment by NickHeiner** [comment]
I'm just going to use our existing `Alert` component for the error messages. Hopefully that looks and feels correct.

**Comment by abbyraskin** [comment]
FYI @gnakm moved the comment error handling here: https://github.com/department-of-veterans-affairs/caseflow/issues/1854

**Comment by kierachell** [comment]
So I changed the `annotations` table to make it unusable and tried to create a new comment:
```
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0721732bbfe6cdde8-172.30.71.3 [appeals.cf.uat.ds.va.gov] [cf565eaf-034b-43cc-a943-5dccb90bb6a4] [172.30.71.3] [CF_Q_317   caseflow@va.gov] [2017-05-09 13:09:54 -0400] Started POST "/document/37/annotation" for 127.0.0.1 at 2017-05-09 13:09:54 -0400                                                                                                                               
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0721732bbfe6cdde8-172.30.71.3 [appeals.cf.uat.ds.va.gov] [cf565eaf-034b-43cc-a943-5dccb90bb6a4] [172.30.71.3] [CF_Q_317   caseflow@va.gov] [2017-05-09 13:09:54 -0400] Processing by AnnotationController#create as JSON                                                                                                                                                               
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0721732bbfe6cdde8-172.30.71.3 [appeals.cf.uat.ds.va.gov] [cf565eaf-034b-43cc-a943-5dccb90bb6a4] [172.30.71.3] [CF_Q_317   caseflow@va.gov] [2017-05-09 13:09:54 -0400]   Parameters: {"annotation"=>{"class"=>"Annotation", "page"=>1, "type"=>"point", "x"=>414.5, "y"=>260, "comment"=>"asdasd", "document_id"=>37}, "document_id"=>"37"}                                            
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0721732bbfe6cdde8-172.30.71.3 [appeals.cf.uat.ds.va.gov] [cf565eaf-034b-43cc-a943-5dccb90bb6a4] [172.30.71.3] [CF_Q_317   caseflow@va.gov] [2017-05-09 13:09:54 -0400] Cache read: out_of_service ({:expires_in=>86400 seconds})                                                                                                                                                       
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0721732bbfe6cdde8-172.30.71.3 [appeals.cf.uat.ds.va.gov] [cf565eaf-034b-43cc-a943-5dccb90bb6a4] [172.30.71.3] [CF_Q_317   caseflow@va.gov] [2017-05-09 13:09:54 -0400]   User Load (1.3ms)  SELECT  "users".* FROM "users" WHERE "users"."css_id" = $1 AND "users"."station_id" = $2 LIMIT 1  [["css_id", "CF_Q_317"], ["station_id", "317"]]
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0721732bbfe6cdde8-172.30.71.3 [appeals.cf.uat.ds.va.gov] [cf565eaf-034b-43cc-a943-5dccb90bb6a4] [172.30.71.3] [CF_Q_317   caseflow@va.gov] [2017-05-09 13:09:54 -0400]    (1.2ms)  BEGIN                                                                                                                                                                                               
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0721732bbfe6cdde8-172.30.71.3 [appeals.cf.uat.ds.va.gov] [cf565eaf-034b-43cc-a943-5dccb90bb6a4] [172.30.71.3] [CF_Q_317   caseflow@va.gov] [2017-05-09 13:09:54 -0400]    (1.3ms)  COMMIT                                                                                                                                                                                              
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0721732bbfe6cdde8-172.30.71.3 [appeals.cf.uat.ds.va.gov] [cf565eaf-034b-43cc-a943-5dccb90bb6a4] [172.30.71.3] [CF_Q_317   caseflow@va.gov] [2017-05-09 13:09:54 -0400]    (1.3ms)  BEGIN                                                                                                                                                                                               
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0721732bbfe6cdde8-172.30.71.3 [appeals.cf.uat.ds.va.gov] [cf565eaf-034b-43cc-a943-5dccb90bb6a4] [172.30.71.3] [CF_Q_317   caseflow@va.gov] [2017-05-09 13:09:54 -0400]   SQL (1.6ms)  INSERT INTO "annotations" ("page", "x", "y", "comment", "document_id", "user_id") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["page", 1], ["x", 414], ["y", 260], ["comment", "asdasd"], ["document_id", 37], ["user_id", 95]]                                                                                                                                                                                                        
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0721732bbfe6cdde8-172.30.71.3 [appeals.cf.uat.ds.va.gov] [cf565eaf-034b-43cc-a943-5dccb90bb6a4] [172.30.71.3] [CF_Q_317   caseflow@va.gov] [2017-05-09 13:09:54 -0400]    (1.3ms)  ROLLBACK                                                                                                                                                                                            
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0721732bbfe6cdde8-172.30.71.3 [appeals.cf.uat.ds.va.gov] [cf565eaf-034b-43cc-a943-5dccb90bb6a4] [172.30.71.3] [CF_Q_317   caseflow@va.gov] [2017-05-09 13:09:54 -0400] Completed 500 Internal Server Error in 12ms (ActiveRecord: 8.0ms)                                                                                                                                               
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0721732bbfe6cdde8-172.30.71.3 [appeals.cf.uat.ds.va.gov] [cf565eaf-034b-43cc-a943-5dccb90bb6a4] [172.30.71.3] [CF_Q_317   caseflow@va.gov] [2017-05-09 13:09:54 -0400]                                                                                                                                                                                                                 
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0721732bbfe6cdde8-172.30.71.3 ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "annotations" does not exist at character 13                                                                                                                                                                                                                                        
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0721732bbfe6cdde8-172.30.71.3 : INSERT INTO "annotations" ("page", "x", "y", "comment", "document_id", "user_id") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"):                                                                                                                                                                                                                       
app/controllers/annotation_controller.rb:7:in `create'                                                                                                                                                                                     
app/middleware/metrics_collector.rb:14:in `call'                                                                                                                                                                                           
app/middleware/metrics_auth.rb:10:in `call'                                                                                                                                                                                              
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0721732bbfe6cdde8-172.30.71.3 172.30.69.231, 172.30.70.242 - - [09/May/2017:13:09:54 -0400] "POST /500 HTTP/1.0" 500 - 0.1881
```
No `Alert` or error showed up.

Sentry did throw an error:
internal-dsva-appeals-sentry-uat-102776152.us-gov-west-1.elb.amazonaws.com/sentry/caseflow-uat/issues/187/

**Comment by NickHeiner** [comment]
@kierachell, alerts for annotations are out of scope for this ticket. We moved that to be #1854. This ticket is only for changing document category and tags.

**Comment by kierachell** [comment]
**PASSED**
K; I changed the AC to reflect that @abbyraskin 
## Messing with tags and labels works
<img width="415" alt="screen shot 2017-05-09 at 4 54 13 pm" src="https://cloud.githubusercontent.com/assets/18075411/25872963/8a9f40b6-34da-11e7-8dae-1f572bf359f8.png">
