### ISSUE TITLE
[Flaky Test] TaskPager.sorted_tasks - undefined method `upcase' for nil:NilClass

### ISSUE THREAD

**Issue by n1zyy** [department-of-veterans-affairs/caseflow#15816]
## Description
We keep seeing variants of [this](https://app.circleci.com/pipelines/github/department-of-veterans-affairs/caseflow/38315/workflows/895c3a79-ad71-4b52-b7f0-6bf31b2d7ed1/jobs/144654) flaky test:

**TaskPager.sorted_tasks when sorting by closest regional office column sorts by regional office city - spec.models.task_pager_spec**

```
Failure/Error: RegionalOffice::CITIES[task.appeal.closest_regional_office][:city].upcase.tr(" ", "_")

NoMethodError:
  undefined method `upcase' for nil:NilClass
./spec/models/task_pager_spec.rb:381:in `block (5 levels) in <top (required)>'
./spec/models/task_pager_spec.rb:380:in `each'
./spec/models/task_pager_spec.rb:380:in `sort_by'
./spec/models/task_pager_spec.rb:380:in `block (4 levels) in <top (required)>'
```

## Background/context/resources

 - Circle CI Error:  [TaskPager.sorted_tasks when sorting by closest regional office column sorts by regional office city - spec.models.task_pager_spec](https://app.circleci.com/pipelines/github/department-of-veterans-affairs/caseflow/38315/workflows/895c3a79-ad71-4b52-b7f0-6bf31b2d7ed1/jobs/144654)
 - Has the test already been skipped in the code?
   - [ ] Skipped
   - [x] Not Skipped

## Approach

Time box this investigation and fix.

Remember that if a test has been skipped for a decent amount of time, it may no longer map to the exact code.

If you reach the end of your time box and don't feel like the solution is in sight:
  - [ ] document the work you've done, including dead ends and research
  - [ ] skip the test in the code
  - [ ] file a follow on ticket
  - [ ] close this issue

**Comment by n1zyy** [comment]
I threw this in and ran the test in a loop:

```ruby
          if RegionalOffice::CITIES[task.appeal.closest_regional_office][:city].nil?
            byebug
          end
```

`closest_regional_office` is "R" when this happens, which is apparently used for virtual hearings and thus has no city.

The question I have now is&mdash;is this just a bad test that assumes city will never be nil (I think it is), or is this problem also reflected in code?

**Comment by n1zyy** [comment]
Hit again here: https://app.circleci.com/pipelines/github/department-of-veterans-affairs/caseflow/38376/workflows/e2fbdbf2-1a7c-4595-9c79-d25511305eb4/jobs/144950

**Comment by n1zyy** [comment]
Whoa -- hit a variant of it I haven't seen before on re-run: https://app.circleci.com/pipelines/github/department-of-veterans-affairs/caseflow/38376/workflows/2260f286-dce0-4ff5-9e98-5b2400251211/jobs/144956
