### ISSUE TITLE
[Flaky Test] User switches hearing type to 'Virtual'

### ISSUE THREAD

**Issue by rubaiyat22** [department-of-veterans-affairs/caseflow#15997]
## Description
```
Failure/Error: expect(hearing.virtual_hearing.judge_email).to eq(nil)

  expected: nil
       got: "trang@bernier.net"

  (compared using ==)
./spec/feature/hearings/virtual_hearings/hearing_details_spec.rb:158:in `block (3 levels) in <top (required)>'
./spec/spec_helper.rb:23:in `block (2 levels) in <top (required)>'
```

```
Failure/Error: expect(find_all("tr").length).to eq(row_count)

  expected: 2
       got: 3

  (compared using ==)
./spec/feature/hearings/virtual_hearings/hearing_details_spec.rb:17:in `block in check_email_event_rows'
./spec/feature/hearings/virtual_hearings/hearing_details_spec.rb:15:in `check_email_event_rows'
./spec/feature/hearings/virtual_hearings/hearing_details_spec.rb:38:in `check_email_event_table'
./spec/feature/hearings/virtual_hearings/hearing_details_spec.rb:190:in `block (3 levels) in <top (required)>'
./spec/spec_helper.rb:23:in `block (2 levels) in <top (required)>'
```

## Background/context/resources

 - Circle CI Error:  https://app.circleci.com/pipelines/github/department-of-veterans-affairs/caseflow/39916/workflows/b8f8315d-ba69-46f9-b2a8-a55ced03addc/jobs/152491/tests#failed-test-1
 - Has the test already been skipped in the code?
   - [ ] Skipped
   - [x] Not Skipped
 - Related Flakes
    + 

## Approach

Time box this investigation and fix.

Remember that if a test has been skipped for a decent amount of time, it may no longer map to the exact code.

If you reach the end of your time box and don't feel like the solution is in sight:
  - [ ] document the work you've done, including dead ends and research
  - [ ] skip the test in the code
  - [ ] file a follow on ticket
  - [ ] close this issue

**Comment by rubaiyat22** [comment]
Not a flake. this was part of WIP PR https://github.com/department-of-veterans-affairs/caseflow/pull/15976
