### ISSUE TITLE
Stats | Page not displaying due to Template Error

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#1604]
# Description
When trying to access the Stats page...I get nothing.

## Reproduction Steps

**Scenario 1 -**

1. Go to`certification/stats`

1. Expect to see stats

1. See **Something went wrong**

**Validated in the following Envrionment(s)**
- [ ] Dev
- [ ] UAT
- [X] Preprod
- [ ] Prod

## Logs:

```
[2017-04-17 13:32:56 -0400]
dsva-appeals-certification-preprod/opt/caseflow-certification/src/log/caseflow-certification.out i-077c72f13a691e3f3-172.30.71.210 ActionView::Template::Error (undefined method `/' for nil:NilClass):
    55:           Overall
    56:         </h4>
    57:         <div class="cf-stat-figure data-rate" data-key="same_period_completions/certifications_started">
    58:           <%= format_rate_stat(:same_period_completions, :certifications_started) %>
    59:         </div>
    60:       </div>
    61:
  app/controllers/certification_stats_controller.rb:42:in `format_rate_stat'
  app/views/certification_stats/show.html.erb:58:in `_app_views_certification_stats_show_html_erb__2809930038073546449_47178112736020'
  app/middleware/metrics_collector.rb:14:in `call'
  app/middleware/metrics_auth.rb:10:in `call'
```

## Sentry:

n/a

## Screenshots
**_Scenario 1 - [Stats Page]_**
<img width="1017" alt="screen shot 2017-04-17 at 1 37 25 pm" src="https://cloud.githubusercontent.com/assets/18075411/25097557/0732ffd8-2373-11e7-9347-fe514e542fc4.png">

**Comment by kierachell** [comment]
**PASSED**

They fine now
