### ISSUE TITLE
Sign And Certify | Populate changes to the DB [2]

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1709]
Populate Sign and Certify data to the DB. See `certification/ConfirmCaseDetails.jsx`, `actions/ConfirmCaseDetails.js`, and `reducers/ConfirmCaseDetails.js` for a pattern to follow.

Acceptance Criteria:

Make selections on /certifications/VACOLS_ID/sign_and_certify.
Click continue.
Reload the page.
Your selections should now be populated with the data from the db.

**Comment by kierachell** [comment]
Populating the fields with invalid values (00/00/0000) causes an interesting 500 error:
```
dsva-appeals-certification-preprod/opt/caseflow-certification/src/log/caseflow-certification.out i-0e0a8f1134448e165-172.30.67.93 [certification.cf.preprod.ds.va.gov] [e9fa0da3-e76a-40ad-8358-49110acdb789] [172.30.67.93] [CASEFLOW_317
  caseflow@va.gov] [2017-05-02 17:39:18 -0400] Started PUT "/certifications/1154402/update_v2" for 127.0.0.1 at 2017-05-02 17:39:18 -0400
dsva-appeals-certification-preprod/opt/caseflow-certification/src/log/caseflow-certification.out i-0e0a8f1134448e165-172.30.67.93 [certification.cf.preprod.ds.va.gov] [e9fa0da3-e76a-40ad-8358-49110acdb789] [172.30.67.93] [CASEFLOW_317
  caseflow@va.gov] [2017-05-02 17:39:18 -0400] Processing by CertificationsController#update_v2 as JSON
dsva-appeals-certification-preprod/opt/caseflow-certification/src/log/caseflow-certification.out i-0e0a8f1134448e165-172.30.67.93 [certification.cf.preprod.ds.va.gov] [e9fa0da3-e76a-40ad-8358-49110acdb789] [172.30.67.93] [CASEFLOW_317
  caseflow@va.gov] [2017-05-02 17:39:18 -0400]   Parameters: {"update"=>{"certifying_office"=>"SIGN", "certifying_username"=>"AND", "certifying_official_name"=>"CERTIFY", "certifying_official_title"=>"CLAIMS_ASSISTANT", "certification_date"=>"00/00/0000"}, "id"=>"1154402", "certification"=>{}}
dsva-appeals-certification-preprod/opt/caseflow-certification/src/log/caseflow-certification.out i-0e0a8f1134448e165-172.30.67.93 [certification.cf.preprod.ds.va.gov] [e9fa0da3-e76a-40ad-8358-49110acdb789] [172.30.67.93] [CASEFLOW_317   caseflow@va.gov] [2017-05-02 17:39:18 -0400] Cache read: out_of_service ({:expires_in=>86400 seconds})
dsva-appeals-certification-preprod/opt/caseflow-certification/src/log/caseflow-certification.out i-0e0a8f1134448e165-172.30.67.93 [certification.cf.preprod.ds.va.gov] [e9fa0da3-e76a-40ad-8358-49110acdb789] [172.30.67.93] [CASEFLOW_317   caseflow@va.gov] [2017-05-02 17:39:18 -0400]   User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."css_id" = $1 AND "users"."station_id" = $2 LIMIT 1  [["css_id", "CASEFLOW_317"], ["station_id", "317"]]
dsva-appeals-certification-preprod/opt/caseflow-certification/src/log/caseflow-certification.out i-0e0a8f1134448e165-172.30.67.93 [certification.cf.preprod.ds.va.gov] [e9fa0da3-e76a-40ad-8358-49110acdb789] [172.30.67.93] [CASEFLOW_317   caseflow@va.gov] [2017-05-02 17:39:18 -0400]    (0.5ms)  BEGIN
dsva-appeals-certification-preprod/opt/caseflow-certification/src/log/caseflow-certification.out i-0e0a8f1134448e165-172.30.67.93 [certification.cf.preprod.ds.va.gov] [e9fa0da3-e76a-40ad-8358-49110acdb789] [172.30.67.93] [CASEFLOW_317
  caseflow@va.gov] [2017-05-02 17:39:18 -0400]    (0.4ms)  COMMIT
dsva-appeals-certification-preprod/opt/caseflow-certification/src/log/caseflow-certification.out i-0e0a8f1134448e165-172.30.67.93 [certification.cf.preprod.ds.va.gov] [e9fa0da3-e76a-40ad-8358-49110acdb789] [172.30.67.93] [CASEFLOW_317
  caseflow@va.gov] [2017-05-02 17:39:18 -0400]   Certification Load (0.7ms)  SELECT  "certifications".* FROM "certifications" LEFT OUTER JOIN certification_cancellations ON                                                                       certifications.id = certification_cancellations.certification_id WHERE "certification_cancellations"."certification_id" IS NULL AND "certifications"."vacols_id" = $1 LIMIT 1  [["vacols_id", "1154402"]]
dsva-appeals-certification-preprod/opt/caseflow-certification/src/log/caseflow-certification.out i-0e0a8f1134448e165-172.30.67.93 [certification.cf.preprod.ds.va.gov] [e9fa0da3-e76a-40ad-8358-49110acdb789] [172.30.67.93] [CASEFLOW_317   caseflow@va.gov] [2017-05-02 17:39:18 -0400]    (0.4ms)  BEGIN
dsva-appeals-certification-preprod/opt/caseflow-certification/src/log/caseflow-certification.out i-0e0a8f1134448e165-172.30.67.93 [certification.cf.preprod.ds.va.gov] [e9fa0da3-e76a-40ad-8358-49110acdb789] [172.30.67.93] [CASEFLOW_317   caseflow@va.gov] [2017-05-02 17:39:18 -0400]    (0.5ms)  ROLLBACK
dsva-appeals-certification-preprod/opt/caseflow-certification/src/log/caseflow-certification.out i-0e0a8f1134448e165-172.30.67.93 [certification.cf.preprod.ds.va.gov] [e9fa0da3-e76a-40ad-8358-49110acdb789] [172.30.67.93] [CASEFLOW_317
  caseflow@va.gov] [2017-05-02 17:39:18 -0400] Completed 500 Internal Server Error in 8ms (ActiveRecord: 3.1ms)
dsva-appeals-certification-preprod/opt/caseflow-certification/src/log/caseflow-certification.out i-0e0a8f1134448e165-172.30.67.93 [certification.cf.preprod.ds.va.gov] [e9fa0da3-e76a-40ad-8358-49110acdb789] [172.30.67.93] [CASEFLOW_317
  caseflow@va.gov] [2017-05-02 17:39:18 -0400]                                                                                                                                                                                             dsva-appeals-certification-preprod/opt/caseflow-certification/src/log/caseflow-certification.out i-0e0a8f1134448e165-172.30.67.93 ActiveRecord::UnknownAttributeError (unknown attribute 'certifying_office' for Certification.):
  app/controllers/certifications_controller.rb:36:in `update_v2'                                                                                                                                                                             app/middleware/metrics_collector.rb:14:in `call'
  app/middleware/metrics_auth.rb:10:in `call'
```

<img width="1139" alt="screen shot 2017-05-02 at 5 39 25 pm" src="https://cloud.githubusercontent.com/assets/18075411/25640668/6e4c7cca-2f5e-11e7-8887-811dfa5bb181.png">

**Comment by slj** [comment]
@amprokop is on it.

**Comment by amprokop** [comment]
@kierachell — #1484 should take care of this.

**Comment by amprokop** [comment]
Closing, finished.
