### ISSUE TITLE
Document list | Alert for filters

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1780]
As a user, I want to know when my search results have been filtered. 

## Dependent story
#1432 Documents List | Categories: filter by one or more category
#1438 Documents List | Issue tags: filter Documents List view by issue tag(s)

## AC
- Styling should be in USWDS information status 
- Copy text below

## Mockups
![image](https://cloud.githubusercontent.com/assets/13420618/25537799/03643aa4-2c0e-11e7-8ab8-08104eae728d.png)

## Copy 
Showing limited results
Documents are currently filtered by [insert categories]. Click here to see all documents.

**Comment by kierachell** [comment]
Seems to be causing a lot of JS errors:
<img width="863" alt="screen shot 2017-04-30 at 9 43 35 am" src="https://cloud.githubusercontent.com/assets/18075411/25564835/8d567b74-2d89-11e7-8c29-0571185699f5.png">

```
application-31b1cd2….js:27 Uncaught TypeError: Cannot read property 'toLowerCase' of null
    at https://certification.cf.preprod.ds.va.gov/assets/application-31b1cd29f9d87b218b9926f4a76358fd9acbed54f39221d0d66a2e9cbf109233.js:27:19055
    at Array.some (native)
    at https://certification.cf.preprod.ds.va.gov/assets/application-31b1cd29f9d87b218b9926f4a76358fd9acbed54f39221d0d66a2e9cbf109233.js:27:19022
    at Array.filter (native)
    at t.S.filterDocuments (https://certification.cf.preprod.ds.va.gov/assets/application-31b1cd29f9d87b218b9926f4a76358fd9acbed54f39221d0d66a2e9cbf109233.js:27:18804)
    at t.S.sortAndFilter (https://certification.cf.preprod.ds.va.gov/assets/application-31b1cd29f9d87b218b9926f4a76358fd9acbed54f39221d0d66a2e9cbf109233.js:27:17684)
    at e.notifyAll (https://certification.cf.preprod.ds.va.gov/assets/application-31b1cd29f9d87b218b9926f4a76358fd9acbed54f39221d0d66a2e9cbf109233.js:19:18185)
    at a.close (https://certification.cf.preprod.ds.va.gov/assets/application-31b1cd29f9d87b218b9926f4a76358fd9acbed54f39221d0d66a2e9cbf109233.js:5:8185)
    at a.closeAll (https://certification.cf.preprod.ds.va.gov/assets/application-31b1cd29f9d87b218b9926f4a76358fd9acbed54f39221d0d66a2e9cbf109233.js:7:20031)
    at a.perform (https://certification.cf.preprod.ds.va.gov/assets/application-31b1cd29f9d87b218b9926f4a76358fd9acbed54f39221d0d66a2e9cbf109233.js:7:19526)
```

**Comment by mdbenjam** [comment]
I am not seeing these errors? How did you get them? Just by filtering and searching?

**Comment by kierachell** [comment]
From `preprod`:

So this one seems to filter ok: 890983
Whereas this case causes errors: 1499662

One potential case is that there's an `unknown` and `other` doctypes that do not seem to filter alphabetically in order (end up being places after all the other doctypes in the list)

**Comment by mdbenjam** [comment]
I think we decided this was likely due to the null comments. Now that we've fixed that, I want to move this back to in validation.

**Comment by kierachell** [comment]
**PASSED**
<img width="1107" alt="screen shot 2017-05-08 at 3 15 33 pm" src="https://cloud.githubusercontent.com/assets/18075411/25820970/3a374e0e-3401-11e7-9474-9e6fab43f372.png">
