### ISSUE TITLE
Document List | Nil Comments cause JS errors and limit functionality

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#1828]
## AC
1. Verify there is non-nil constraint on the comment field in the annotation table.
1. Verify that saving an empty comment on the frontend acts as cancelling the comment.
1. Verify that editing a comment to contain no text triggers the delete flow (delete modal -> cancel/delete)

# Description
Using preprod cases such as:
- 1499662

more here: https://github.com/department-of-veterans-affairs/appeals-qa/blob/master/TestData/TestCaseflowData.md

Maybe caused by `nil` or "" comments

## Reproduction Steps

**Scenario 1 -**

1. Go to Reader Document List
1. Try Expand all
1. Try filtering using the Search 
1. 

**Validated in the following Envrionment(s)**
- [ ] Dev
- [ ] UAT
- [ ] Preprod
- [ ] Prod

#### Expand all:
```
application-c8a2f85….js:7 Uncaught TypeError: Cannot read property 'getHostNode' of null
    at Object.getHostNode (application-c8a2f85….js:7)
    at d.getHostNode (application-c8a2f85….js:39)
    at Object.getHostNode (application-c8a2f85….js:7)
    at Object.updateChildren (application-c8a2f85….js:39)
    at h._reconcilerUpdateChildren (application-c8a2f85….js:40)
    at h._updateChildren (application-c8a2f85….js:40)
    at h.updateChildren (application-c8a2f85….js:40)
    at h._updateDOMChildren (application-c8a2f85….js:39)
    at h.updateComponent (application-c8a2f85….js:39)
    at h.receiveComponent (application-c8a2f85….js:39)
```
```
Uncaught TypeError: Cannot read property 'toString' of null
    at t.value (application-c8a2f85….js:11)
    at d._renderValidatedComponentWithoutOwnerOrContext (application-c8a2f85….js:39)
    at d._renderValidatedComponent (application-c8a2f85….js:39)
    at d.performInitialMount (application-c8a2f85….js:39)
    at d.mountComponent (application-c8a2f85….js:39)
    at Object.mountComponent (application-c8a2f85….js:7)
    at h.mountChildren (application-c8a2f85….js:40)
    at h._createInitialChildren (application-c8a2f85….js:39)
    at h.mountComponent (application-c8a2f85….js:39)
    at Object.mountComponent (application-c8a2f85….js:7)
```

#### Searching via text field
```
application-c8a2f85….js:29 Uncaught TypeError: Cannot read property 'toLowerCase' of null
    at https://certification.cf.preprod.ds.va.gov/assets/application-c8a2f8553178e44c0cb38140ccab82f82b6e6029f8bee4b257694230328f0224.js:29:32076
    at Array.reduce (native)
    at u (https://certification.cf.preprod.ds.va.gov/assets/application-c8a2f8553178e44c0cb38140ccab82f82b6e6029f8bee4b257694230328f0224.js:29:32036)
    at https://certification.cf.preprod.ds.va.gov/assets/application-c8a2f8553178e44c0cb38140ccab82f82b6e6029f8bee4b257694230328f0224.js:29:32511
    at Array.some (native)
    at https://certification.cf.preprod.ds.va.gov/assets/application-c8a2f8553178e44c0cb38140ccab82f82b6e6029f8bee4b257694230328f0224.js:29:32458
    at f (https://certification.cf.preprod.ds.va.gov/assets/application-c8a2f8553178e44c0cb38140ccab82f82b6e6029f8bee4b257694230328f0224.js:2:31862)
    at Function.cs [as filter] (https://certification.cf.preprod.ds.va.gov/assets/application-c8a2f8553178e44c0cb38140ccab82f82b6e6029f8bee4b257694230328f0224.js:4:7950)
    at f (https://certification.cf.preprod.ds.va.gov/assets/application-c8a2f8553178e44c0cb38140ccab82f82b6e6029f8bee4b257694230328f0224.js:5:3392)
    at Function.ts [as thru] (https://certification.cf.preprod.ds.va.gov/assets/application-c8a2f8553178e44c0cb38140ccab82f82b6e6029f8bee4b257694230328f0224.js:4:7102)
```

#### 

## Screenshots
**_Scenario 1 - [Not functioning filtering]_**
<img width="1364" alt="screen shot 2017-05-03 at 9 18 04 am" src="https://cloud.githubusercontent.com/assets/18075411/25662154/734546fc-2fe1-11e7-828f-cb720d135c4c.png">

**Comment by kierachell** [comment]
**PASSED**
![nilcomment](https://cloud.githubusercontent.com/assets/18075411/25820632/f709705e-33ff-11e7-96a7-a46e0e814758.gif)
