### ISSUE TITLE
[2] Check that needed info is present before attempting to certify

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1894]
If all the necessary fields are not filled out (hearing preference, representative type, etc etc), throw a 500 from the server when the user is attempting to certify.

Acceptance criteria:
- If you manually skip from `certifications/ID/check_documents` to `certifications/ID/sign_and certify`, then attempt to certify, a 500 page should be displayed.

**Comment by kierachell** [comment]
## The error type is not initialized, so there is a 500 but for a wrong reason
```
BEGIN

dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0066370949bc0b3e1-172.30.71.28 [appeals.cf.uat.ds.va.gov] [f1a037b0-b2ae-42f0-ab40-5321a2b09fd3] [172.30.71.28] [CASEFLOW_283   caseflow@va.gov] [2017-05-31 16:02:52 -0400]   SQL (1.6ms)  UPDATE "certifications" SET "certifying_official_name" = $1, "certifying_official_title" = $2, "updated_at" = $3 WHERE "certifications"."id" = $4  [["certifying_official_name", "asd"], ["certifying_official_title", "RATING_SPECIALIST"], ["updated_at", "2017-05-31 20:02:52.510186"], ["id", 10321]]

dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0066370949bc0b3e1-172.30.71.28 [appeals.cf.uat.ds.va.gov] [f1a037b0-b2ae-42f0-ab40-5321a2b09fd3] [172.30.71.28] [CASEFLOW_283   caseflow@va.gov] [2017-05-31 16:02:52 -0400]    (3.8ms)  COMMIT

dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0066370949bc0b3e1-172.30.71.28 [appeals.cf.uat.ds.va.gov] [f1a037b0-b2ae-42f0-ab40-5321a2b09fd3] [172.30.71.28] [CASEFLOW_283   caseflow@va.gov] [2017-05-31 16:02:52 -0400] Completed 500 Internal Server Error in 23ms (ActiveRecord: 13.5ms)

dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0066370949bc0b3e1-172.30.71.28 [appeals.cf.uat.ds.va.gov] [f1a037b0-b2ae-42f0-ab40-5321a2b09fd3] [172.30.71.28] [CASEFLOW_283   caseflow@va.gov] [2017-05-31 16:02:52 -0400]

dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0066370949bc0b3e1-172.30.71.28 NameError (uninitialized constant 
CertificationsController::CertificationMissingData):                         app/controllers
/certifications_controller.rb:105:in `validate_data_presence_v2'                                                                                                                                                            
app/controllers/certifications_controller.rb:50:in `certify_v2'                                                                                                                                                                            
app/middleware/metrics_collector.rb:14:in `call'                                                                                                                                                                                           
app/middleware/metrics_auth.rb:10:in `call'
```

**Comment by amprokop** [comment]
@nemodjuric — can you take a look at this?

**Comment by kierachell** [comment]
# Why is the following certification not working? What data is being validated?


### With empty VACOLS data:
<img width="1047" alt="screen shot 2017-06-02 at 12 46 04 pm" src="https://cloud.githubusercontent.com/assets/18075411/26736466/22706732-4794-11e7-99bf-997f12dc683e.png">


### Error:

```
Certification Load (1.1ms)  SELECT  "certifications".* FROM "certifications" LEFT OUTER JOIN certification_cancellations ON                                                                                     certifications.id = certification_cancellations.certification_id WHERE "certification_cancellations"."certification_id" IS NULL AND "certifications"."vacols_id" = $1 LIMIT 1  [["vacols_id", "1662403"]]
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-05151c349fbac64b3-172.30.67.23 [appeals.cf.uat.ds.va.gov] [185f7704-3a86-407f-a8af-b6c348b2eeca] [172.30.67.23] [CASEFLOW_317   caseflow@va.gov] [2017-06-02 13:02:17 -0400]    (0.6ms)  BEGIN
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-05151c349fbac64b3-172.30.67.23 [appeals.cf.uat.ds.va.gov] [185f7704-3a86-407f-a8af-b6c348b2eeca] [172.30.67.23] [CASEFLOW_317   caseflow@va.gov] [2017-06-02 13:02:17 -0400]   SQL (0.8ms)  UPDATE "certifications" SET "certifying_official_name" = $1, "certifying_official_title" = $2, "updated_at" = $3 WHERE "certifications"."id" = $4  [["certifying_official_name", "huh"], ["certifying_official_title", "CLAIMS_ASSISTANT"], ["updated_at", "2017-06-02 17:02:17.609054"], ["id", 10371]]
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-05151c349fbac64b3-172.30.67.23 [appeals.cf.uat.ds.va.gov] [185f7704-3a86-407f-a8af-b6c348b2eeca] [172.30.67.23] [CASEFLOW_317   caseflow@va.gov] [2017-06-02 13:02:17 -0400]    (3.2ms)  COMMIT
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-05151c349fbac64b3-172.30.67.23 [appeals.cf.uat.ds.va.gov] [185f7704-3a86-407f-a8af-b6c348b2eeca] [172.30.67.23] [CASEFLOW_317   caseflow@va.gov] [2017-06-02 13:02:17 -0400] Completed 500 Internal Server Error in 17ms (ActiveRecord: 8.1ms)
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-05151c349fbac64b3-172.30.67.23 172.30.66.175 - dsva [02/Jun/2017:13:02:17 -0400] "GET /metrics HTTP/1.0" 200 - 0.0985
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-05151c349fbac64b3-172.30.67.23 [appeals.cf.uat.ds.va.gov] [185f7704-3a86-407f-a8af-b6c348b2eeca] [172.30.67.23] [CASEFLOW_317   caseflow@va.gov] [2017-06-02 13:02:17 -0400]
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-05151c349fbac64b3-172.30.67.23 Caseflow::Error::CertificationMissingData (Caseflow::Error::CertificationMissingData):
  app/controllers/certifications_controller.rb:105:in `validate_data_presence_v2'
  app/controllers/certifications_controller.rb:50:in `certify_v2'
  app/middleware/metrics_collector.rb:14:in `call'
  app/middleware/metrics_auth.rb:10:in `call'
```

### Data in the DB:
```
#<Certification id: 10371, vacols_id: "1662403", already_certified: false, vacols_data_missing: false, nod_matching_at: "2017-06-02 17:01:47", soc_matching_at: "2017-06-02 17:01:47", form9_matching_at: "2017-06-02 17:01:47", ssocs_r
equired: true, ssocs_matching_at: "2017-06-02 17:01:47", form8_started_at: "2017-06-02 17:01:47", completed_at: nil, created_at: "2017-06-02 17:01:45", updated_at: "2017-06-02 17:02:17", user_id: nil, bgs_representative_type: "Service Organization", bgs_representative_name: "RHODE ISLAND DIVISION OF VETERANS AFFAIRS", vacols_representative_type: "Other", vacols_representative_name: nil, representative_type: "Other", representative_name: nil, hearing_change_doc_found
_in_vbms: true, form9_type: nil, vacols_hearing_preference: "travel_board", hearing_preference: "VIDEO", certifying_office: "Seattle, WA", certifying_username: "RO46", certifying_official_name: "huh", certifying_official_title: "CLAIMS_ASSISTANT", certification_date: "2017-06-02", poa_matches: false, poa_correct_in_vacols: true, poa_correct_in_bgs: false, bgs_rep_address_line_1: nil, bgs_rep_address_line_2: nil, bgs_rep_address_line_3: nil, bgs_rep_city: nil, bgs_re
p_country: nil, bgs_rep_state: nil, bgs_rep_zip: nil>
```

**Comment by amprokop** [comment]
@nemodjuric — can you take a look at this once you finish your current task?

**Comment by kierachell** [comment]
**PASSED**
```
Caseflow::Error::CertificationMissingData (Caseflow::Error::CertificationMissingData):
  app/controllers/certifications_controller.rb:105:in `validate_data_presence_v2'
  app/controllers/certifications_controller.rb:50:in `certify_v2'
  app/middleware/metrics_collector.rb:14:in `call'
  app/middleware/metrics_auth.rb:10:in `call'
```
