### ISSUE TITLE
Implement API key authentication

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1915]
## Acceptance criteria
- Enforce that a valid API key is passed with each call to the appeals endpoint
- If an invalid or missing key is passed, return a 401 response code

## Technical notes
- API keys should be encrypted in the DB

**Comment by shanear** [comment]
@kierachell let me know if you need me to make you an ApiKey. You can also follow the directions here: https://github.com/department-of-veterans-affairs/caseflow/pull/2108

**Comment by kierachell** [comment]
## Getting token to work:
```
[appeals.cf.uat.ds.va.gov] [f4334c3c-f0b7-463f-b174-eb80cc38fc55] [172.30.67.150] [2017-05-23 18:40:07 -0400] API authenticated by QA
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0092423e11465fa94-172.30.67.150 [appeals.cf.uat.ds.va.gov] [f4334c3c-f0b7-463f-b174-eb80cc38fc55] [172.30.67.150] [2017-05-23 18:40:07 -0400] Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.6ms)
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0092423e11465fa94-172.30.67.150 [appeals.cf.uat.ds.va.gov] [f4334c3c-f0b7-463f-b174-eb80cc38fc55] [172.30.67.150] [2017-05-23 18:40:07 -0400]  dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0092423e11465fa94-172.30.67.150 NoMethodError (undefined method `length' for nil:NilClass):
  app/models/appeal.rb:345:in `for_api'                                                                                                                                                                                                         app/controllers/api/v1/appeals_controller.rb:17:in `appeals'
  app/controllers/api/v1/appeals_controller.rb:7:in `index'                                                                                                                                                                                     app/middleware/metrics_collector.rb:14:in `call'                                                                                                                                                                                              app/middleware/metrics_auth.rb:10:in `call'
```
So it does authorize, but calls 500 if no SSN is passed. ok

## Let's try with SSN now:
```
curl -i -H 'ssn: 516517673 Authorization: Token ****' -X GET https://appeals.cf.uat.ds.va.gov/api/v1/appeals
HTTP/1.1 401 Unauthorized
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Tue, 23 May 2017 22:41:42 GMT
Server: nginx/1.10.2
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: b456ba13-cd97-4c58-911f-acc653f47258
X-Runtime: 0.002649
X-XSS-Protection: 1; mode=block
Content-Length: 25
Connection: keep-alive
```

Why

**Comment by kierachell** [comment]
**PASSED**

```
HTTP/1.1 200 OK
Cache-Control: max-age=0, private, must-revalidate
Content-Type: application/json; charset=utf-8
Date: Wed, 24 May 2017 12:51:28 GMT
ETag: W/"75668268de042ec5bad0c12680a1d4df"
Server: nginx/1.10.2
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: b26a8165-326b-4144-abed-fa074ad0b94b
X-Runtime: 1.982981
X-XSS-Protection: 1; mode=block
Content-Length: 482
Connection: keep-alive

{"data":[{"id":"1161479","type":"appeals","attributes":{"type":"original","active":false,"prior_decision_date":null,"events":[{"type":"nod","date":"1999-06-23"},{"type":"soc","date":"1999-09-30"},{"type":"form9","date":"2000-02-22"},{"type":"certified","date":"2002-08-08"},{"type":"bva_final_decision","date":"2017-05-06"}]}},{"id":"2648259","type":"appeals","attributes":{"type":"original","active":true,"prior_decision_date":null,"events":[{"type":"nod","date":"2012-08-29"}]}}]}
```
