### ISSUE TITLE
Return all appeals associated with a veteran

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1930]
## Acceptance Criteria
- The endpoint `/api/v1/appeals` should return a list of all appeals associated with the veteran with the passed SSN (it's passed in the header according to the API docs below).
- The response should be JSON API compliant, and return the following attributes along with the appeal according to the API spec:
    - active
    - type
    - events
- Events with the following types should be added based on whether they have happened: "nod", "soc", "form9", "ssoc", "certified", "bva_final_decision", "bva_remand", "field_grant", "withdrawn", "merged"
- It should only exist with the feature flag `:appeals_status` turned on

## Technical Notes
- the following event types will be handled in another story: activated, hearing_held, hearing_cancelled, hearing_no_show, cavc_decision
- proper handling of 404s & 500s will be handled in another story
- API spec location: https://github.com/department-of-veterans-affairs/appeals-pm/pull/1289

**Comment by kierachell** [comment]
## Blank SSN check failed:
```
curl -i -H 'ssn: ' -X GET https://appeals.cf.uat.ds.va.gov/api/v1/appeals
HTTP/1.1 200 OK
Cache-Control: max-age=0, private, must-revalidate
Content-Type: application/json; charset=utf-8
Date: Tue, 23 May 2017 11:54:40 GMT
ETag: W/"b4ec3340844cddfa750828caff9c7b6d"
Server: nginx/1.10.2
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: feaf38e4-c4fc-4a73-8ec3-20fc9923d2c2
X-Runtime: 3.174723
X-XSS-Protection: 1; mode=block
Content-Length: 565
Connection: keep-alive

{"data":[{"id":"779106","type":"appeals","attributes":{"type":"post_remand","active":false,"prior_decision_date":"1996-09-16","events":[{"type":"nod","date":"1993-12-30"},{"type":"soc","date":"1995-01-12"},{"type":"form9","date":"1995-03-13"},{"type":"bva_final_decision","date":"1998-04-24"}]}},{"id":"523731","type":"appeals","attributes":{"type":"original","active":false,"prior_decision_date":null,"events":[{"type":"nod","date":"1993-12-30"},{"type":"soc","date":"1
995-01-12"},{"type":"form9","date":"1995-03-13"},{"type":"bva_remand","date":"1996-09-16"}]}}]}
```

## Returning the HTML 404 page instead?
```
curl -i -H 'ssn: 516517674' -X GET https://appeals.cf.uat.ds.va.gov/api/v1/appeals
HTTP/1.1 404 Not Found
Content-Type: text/html; charset=utf-8
Date: Tue, 23 May 2017 12:06:11 GMT
Server: nginx/1.10.2
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: da91df94-fb6b-4728-8775-ccc94048ee87
X-Runtime: 0.214803
X-XSS-Protection: 1; mode=block
Content-Length: 5727
Connection: keep-alive

<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv='X-UA-Compatible' content='IE=edge'>

  <title>Caseflow </title>


  <link rel="stylesheet" media="all" href="/assets/application-23adf0632c5a6a04ac6241d209627a0f4872cd2242f84e71430482d8e53b3595.css" />

    <script src="/assets/application-6a0484e03fd74d444fcd495fdb075963aa230cb06a628425d612af36b5dc504d.js"></script>

  <meta name="csrf-param" content="authenticity_token" />
<meta name="csrf-token" content="KyVJV9LRI7A9wwnRBPmiBe0oB9aO5zMVIzOz++geT19FFW1FL4PxS0XJTDHuPiACuZuQZXtvJgAfpiYOErvRxA==" />



  <meta name="viewport" content="width=device-width, initial-scale=1.0" /> ....
```
**Followed by**
```
[appeals.cf.uat.ds.va.gov] [009f9796-e583-49f1-b588-e3a87064431c] [172.30.67.226] [2017-05-23 08:08:20 -0400
] Completed 404 Not Found in 219ms (ActiveRecord: 108.4ms)
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-046c4c34c5c67c63b-172.30.67.226 [appeals.cf.uat.ds.va.gov] [009f9796-e583-49f1-b588-e3a87064431c] [172.30.67.226] [2017-05-23 08:08:20 -0400
]
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-046c4c34c5c67c63b-172.30.67.226 ActiveRecord::RecordNotFound (Couldn't find VACOLS::Correspondent):
  app/services/appeal_repository.rb:42:in `block in appeals_by_appellant_ssn'
  app/services/metrics_service.rb:12:in `block in record'
  app/services/metrics_service.rb:11:in `record'
  app/services/appeal_repository.rb:39:in `appeals_by_appellant_ssn'
  app/models/appeal.rb:341:in `for_api'
  app/controllers/api/v1/appeals_controller.rb:15:in `appeals'
  app/controllers/api/v1/appeals_controller.rb:5:in `index'
  app/middleware/metrics_collector.rb:14:in `call'
  app/middleware/metrics_auth.rb:10:in `call'
```

**Comment by shanear** [comment]
404's are out of scope:
> proper handling of 404s & 500s will be handled in another story

will fix the other two issues

**Comment by kierachell** [comment]
**PASSED**
```
HTTP/1.1 200 OK
Cache-Control: max-age=0, private, must-revalidate
Content-Type: application/json; charset=utf-8
Date: Wed, 24 May 2017 12:51:28 GMT
ETag: W/"75668268de042ec5bad0c12680a1d4df"
Server: nginx/1.10.2
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: b26a8165-326b-4144-abed-fa074ad0b94b
X-Runtime: 1.982981
X-XSS-Protection: 1; mode=block
Content-Length: 482
Connection: keep-alive

{"data":[{"id":"1161479","type":"appeals","attributes":{"type":"original","active":false,"prior_decision_date":null,"events":[{"type":"nod","date":"1999-06-23"},{"type":"soc","date":"1999-09-30"},{"type":"form9","date":"2000-02-22"},{"type":"certified","date":"2002-08-08"},{"type":"bva_final_decision","date":"2017-05-06"}]}},{"id":"2648259","type":"appeals","attributes":{"type":"original","active":true,"prior_decision_date":null,"events":[{"type":"nod","date":"2012-08-29"}]}}]}
```
