### ISSUE TITLE
Return activated event on Appeals API

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#2082]
## Acceptance criteria
- Verify that for appeals that have been activated at the board, add an event with the type `"activated"` to the `events` array on the appeals api with the date of activation.

## Technical Notes
- Chat with @cmgiven about how to calculate this.

**Comment by cmgiven** [comment]
Let's use FOLDER.TIDKTIME for this one. Note that this is actually the completion of Case Review, but it'll prevent premature activation.

**Comment by kierachell** [comment]
### For SSN 163278285
```
ActiveModel::MissingAttributeError (missing attribute: clsdate):
  app/models/hearing.rb:40:in `block in load_from_vacols'
  app/models/hearing.rb:35:in `tap'
  app/models/hearing.rb:35:in `load_from_vacols'
  app/repositories/hearing_repository.rb:14:in `block in hearings_for'                                                                                                                                                                       app/repositories/hearing_repository.rb:14:in `hearings_for'
  app/repositories/hearing_repository.rb:8:in `hearings_for_appeal'
  app/models/appeal.rb:97:in `hearings'
  app/models/appeal_events.rb:50:in `hearing_events'                                                                                                                                                                                         app/models/appeal_events.rb:14:in `all'
  app/models/appeal.rb:85:in `events'
  app/models/appeal.rb:317:in `latest_event_date'
  app/models/appeal.rb:369:in `each'
  app/models/appeal.rb:369:in `sort_by'                                                                                                                                                                                                      app/models/appeal.rb:369:in `for_api'
  app/controllers/api/v1/appeals_controller.rb:17:in `appeals'
  app/controllers/api/v1/appeals_controller.rb:7:in `index'
  app/middleware/metrics_collector.rb:14:in `call'                                                                                                                                                                                           app/middleware/metrics_auth.rb:10:in `call'
```

**Comment by kierachell** [comment]
**PASSED**
`apiRes.first.data.map(&:attributes).map(&:events)`
```
#<OpenStruct type="ssoc", date="2003-01-21">, #<OpenStruct type="ssoc", date="2005-01-26">, #<OpenStruct type="ssoc", date="2006-07-18">, #<OpenStruct type="bva_remand", date="2017-05-08">],
 [#<OpenStruct type="activated", date="2007-10-18">, #<OpenStruct type="ssoc", date="2008-07-22">, #<OpenStruct type="ssoc", date="2008-07-25">, #<OpenStruct type="bva_remand", date="2017-05-05">],
 [#<OpenStruct type="activated", date="2012-12-20">, #<OpenStruct type="bva_remand", date="2017-04-30">],
```
