### ISSUE TITLE
[5] If the POA name is stored in the VACOLS REP table, fetch the name from that table, save it, and send it to the client

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2090]
If Other (code: "O"), Attorney (code: "T"), Agent (code "U"), or One Time Representative (code: "W") is found in `brieff.bfso`, the representative name is meant to be stored in a separate table. 

We can fetch that table using STAFKEY to look up the CORRES table. Use  https://github.com/department-of-veterans-affairs/appeals-pm/blob/master/VA%20Tech%20System%20Documentation/VACOLS/VACOLS%20Database%20Tables.csv to get some context on how the VACOLS DB works.

Let's fetch that table in our `PowerOfAttorneyRepository` and save the POA name, and pass it down to the client. Save the rep name in `vacols_representative_name`, and concatenate the first name, middle initial, last name, and suffix fields in vacols.

If first name and last name fields in the REP table are blank (working on the assumption that it is not reasonable to have a rep name that contains only a middle initial and a suffix), leave `vacols_representative_name` blank as well. On the client, we'll then display "Representative Name Not Found" or some such.

Let's add some fake data to cover the happy path (we can use 124C for this purpose), and tests that cover the unhappy path (or fake data too if the dev is inclined).

### Acceptance Criteria ###
- If `brieff.bfso` contains Other (code: "O"), Attorney (code: "T"), Agent (code "U"), or One Time Representative (code: "W"), upon starting certification, `vacols_representative_name` should be saved on the Certification table with information from the REP table
  - `vacols_representative_name` should be set to a concatenation of the first name, middle initial, last name, and suffix fields in vacols.
  - If the first name and last name fields are blank in the REP table, `vacols_representative_name` should be blank as well

**Comment by aroltsch** [comment]
`vacols_representative_type` should also be updated.

**Comment by kierachell** [comment]
## No POA found error:
```
</env:Header><env:Body><tns:findPOAsByFileNumbers><fileNumbers>516517678</fileNumbers></tns:findPOAsByFileNumbers></env:Body></env:Envelope>                                                                                                                                                                                                            dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0066370949bc0b3e1-172.30.71.28 D, [2017-05-31T15:31:18.554590 #2869] DEBUG -- : HTTPI POST request to beplinktest.vba.va.gov (httpclient)   dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0066370949bc0b3e1-172.30.71.28 I, [2017-05-31T15:31:18.858380 #2869]  INFO -- : SOAP response (status 200)                                  dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0066370949bc0b3e1-172.30.71.28 D, [2017-05-31T15:31:18.858464 #2869] DEBUG -- : <?xml version='1.0' encoding='UTF-8'?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Header><work:WorkContext xmlns:work="http://oracle.com/weblogic/soap/workarea/">rO0ABXdUAB13ZWJsb2dpYy5hcHAuQ29ycG9yYXRlRGF0YUVBUgAAANYAAAAjd2VibG9naWMud29ya2FyZWEuU3RyaW5nV29ya0NvbnRleHQABjEwLjIuMAAA</work:WorkContext></S:Header><S:Body><ns2:findPOAsByFileNumbersResponse xmlns:ns2="http://org.services.vetsnet.vba.va.gov/"><return><fileNumber>516517678</fileNumber><message>No POA found for 600161052</message><ptcpntId>600161052</ptcpntId></return></ns2:findPOAsByFileNumbersResponse></S:Body></S:Envelope>                                                                                                                                                       
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0066370949bc0b3e1-172.30.71.28 [appeals.cf.uat.ds.va.gov] [bbf4a0e9-8b9e-41bf-873e-16992903f964] [172.30.71.28] [CASEFLOW_283   caseflow@va.gov] [2017-05-31 15:31:18 -0400] FINISHED BGS: fetch veteran info for file number: 516517678:   0.010000   0.000000   0.010000 (  0.668979)                                                                                                
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0066370949bc0b3e1-172.30.71.28 [appeals.cf.uat.ds.va.gov] [bbf4a0e9-8b9e-41bf-873e-16992903f964] [172.30.71.28] [CASEFLOW_283   caseflow@va.gov] [2017-05-31 15:31:18 -0400] Completed 500 Internal Server Error in 8297ms (ActiveRecord: 549.0ms)                                                                                                                                     
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0066370949bc0b3e1-172.30.71.28 172.30.66.175 - dsva [31/May/2017:15:31:18 -0400] "GET /metrics HTTP/1.0" 200 - 0.0292                       
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0066370949bc0b3e1-172.30.71.28 [appeals.cf.uat.ds.va.gov] [bbf4a0e9-8b9e-41bf-873e-16992903f964] [172.30.71.28] [CASEFLOW_283   caseflow@va.gov] [2017-05-31 15:31:19 -0400]
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0066370949bc0b3e1-172.30.71.28 NoMethodError (undefined method `[]' for nil:NilClass):                                                        
app/mappers/power_of_attorney_mapper.rb:97:in `get_poa_from_bgs_poa'
app/services/external_api/bgs_service.rb:46:in `fetch_poa_by_file_number'                                                                                                                                                                  
app/models/power_of_attorney.rb:31:in `load_bgs_record!'                                                                                                                                                                                   
app/models/appeal.rb:97:in `power_of_attorney'                                                                                                                                                                                             
app/models/certification.rb:32:in `fetch_power_of_attorney!'                                                                                                                                                                               
app/controllers/certifications_controller.rb:14:in `new'                                                                                                                                                                                   
app/middleware/metrics_collector.rb:14:in `call'                                                                                                                                                                                           
app/middleware/metrics_auth.rb:10:in `call'
```

**Comment by amprokop** [comment]
Cool, looks like we have to handle that error.

**Comment by amprokop** [comment]
@aroltsch — think you might have time to take this on in the next couple days?

**Comment by aroltsch** [comment]
@amprokop I have time

**Comment by amprokop** [comment]
we should discuss how to solve this in Ruby-bgs potentially!

**Comment by aroltsch** [comment]
@kierachell Re: https://github.com/department-of-veterans-affairs/caseflow/issues/2090#issuecomment-305661020. This a question to @amprokop and @cmgiven. We only look up the REP table if brieff.bfso has the following code: Other (code: "O"), Attorney (code: "T"), Agent (code "U"), or One Time Representative (code: "W") .  

In the case you described above for vacols_id 888901, the brieff.bfso has a letter "L" which means "No Representative", short: "None". That's why we also set `vacols_representative_type` to "None" in the certifications table and don't even look in the REP table (maybe we should?). 

Also, I don't know where this error is coming from:
```undefined method `vacols_representative_type=' for class `Appeal'```

**Comment by kierachell** [comment]
So the *AC* should say:
- do not even look at `REP` table when `BFSO=L`

**Comment by kierachell** [comment]
### So what if `BFSO` matches a type, but there's not info the REP table?
<img width="1047" alt="screen shot 2017-06-02 at 12 46 04 pm" src="https://cloud.githubusercontent.com/assets/18075411/26735813/76ce7c0e-4791-11e7-8d57-ebff19351f7f.png">

**Comment by amprokop** [comment]
When merged, https://github.com/department-of-veterans-affairs/caseflow/pull/2235 should solve this

**Comment by aroltsch** [comment]
#2235 is merged

**Comment by kierachell** [comment]
**PASSED**

## Test case O
```
    BFKEY   BFCORLID BFCORKEY SNAMEF SNAMEL       SSN SNOTES BFDC BFMPRO BF41STAT                BFDNOD                BFDSOC                 BFD19               BFSSOC1               BFSSOC2
1 2367429 062610190C   197071 TOYOTA  MIKAR 062610190    uat <NA>    ADV     <NA> 2017-02-22 11:03:05.0 2016-11-14 11:03:05.0 2016-08-06 11:03:05.0 2017-03-04 11:03:05.0 2017-01-03 11:03:05.0
  BFSSOC3 BFSSOC4 BFSSOC5 BFSO BFHR BFTBIND  REPKEY REPTYPE REPFIRST      REPLAST                   REPADDR1
1    <NA>    <NA>    <NA>    O    1    <NA> 2367429       G    ALLEN GUMPERBERGER DISABLED AMERICAN VETERANS
```
<img width="737" alt="screen shot 2017-06-08 at 7 25 49 am" src="https://user-images.githubusercontent.com/18075411/26926436-b66d6e9a-4c1b-11e7-96cf-15075043f73d.png">

## Test Case T
```
    BFKEY   BFCORLID BFCORKEY SNAMEF SNAMEL       SSN SNOTES BFDC BFMPRO BF41STAT                BFDNOD                BFDSOC                 BFD19               BFSSOC1               BFSSOC2
1 1870418 796127501C CK743348    PAT      P 796127501    uat <NA>    ADV     <NA> 2017-02-22 14:32:35.0 2016-11-14 14:32:35.0 2016-08-06 14:32:35.0 2017-03-04 14:32:35.0 2017-01-03 14:32:35.0
  BFSSOC3 BFSSOC4 BFSSOC5 BFSO BFHR BFTBIND  REPKEY REPTYPE REPFIRST REPLAST      REPADDR1
1    <NA>    <NA>    <NA>    T    2    <NA> 1870418       A     ERIN  RASHID PO BOX 180294
```

<img width="745" alt="screen shot 2017-06-08 at 7 28 29 am" src="https://user-images.githubusercontent.com/18075411/26926524-1528788a-4c1c-11e7-8064-736c12afcb2e.png">


## Test Case U
```
    BFKEY   BFCORLID BFCORKEY  SNAMEF SNAMEL       SSN SNOTES BFDC BFMPRO BF41STAT                BFDNOD                BFDSOC                 BFD19               BFSSOC1               BFSSOC2
1 1733624 513451729C CK665294 Carolyn Helder 513451729    uat <NA>    ADV     <NA> 2017-02-22 12:17:18.0 2016-11-14 12:17:18.0 2016-08-06 12:17:18.0 2017-03-04 12:17:18.0 2017-01-03 12:17:18.0
                BFSSOC3               BFSSOC4               BFSSOC5 BFSO BFHR BFTBIND  REPKEY REPTYPE REPFIRST REPLAST       REPADDR1
1 2010-12-17 00:00:00.0 2012-01-13 00:00:00.0 2013-04-09 00:00:00.0    U    2    <NA> 1733624       G  STEPHEN  VAUGHN 19 FOREST PKWY
```
<img width="891" alt="screen shot 2017-06-08 at 7 33 35 am" src="https://user-images.githubusercontent.com/18075411/26926744-ccd852d4-4c1c-11e7-9dd2-7fb72a02a0f1.png">

**Comment by kierachell** [comment]
## Currently we are not fetching VACOLS POA from `REPADDR1` if BFSO = `O`...
```
    BFKEY   BFCORLID BFCORKEY  SNAMEF SNAMEL       SSN SNOTES BFDC BFMPRO BF41STAT                BFDNOD                BFDSOC                 BFD19
1 1733624 513451729C CK665294 Carolyn Helder 513451729    uat <NA>    ADV     <NA> 2017-02-22 12:17:18.0 2016-11-14 12:17:18.0 2016-08-06 12:17:18.0
                BFSSOC1               BFSSOC2               BFSSOC3               BFSSOC4               BFSSOC5 BFSO BFHR BFTBIND  REPKEY REPTYPE REPFIRST REPMI
1 2017-03-04 12:17:18.0 2017-01-03 12:17:18.0 2010-12-17 00:00:00.0 2012-01-13 00:00:00.0 2013-04-09 00:00:00.0    O    2    <NA> 1733624       G     <NA>  <NA>
  REPLAST                                       REPADDR1 REPST REPZIP
1    <NA> MASSACHUSETTS DEPARTMENT OF VETERANS' SERVICES  <NA>   <NA>
```

<img width="981" alt="screen shot 2017-06-11 at 12 30 55 pm" src="https://user-images.githubusercontent.com/18075411/27012652-d48c660a-4ea1-11e7-9dff-0da7f5316191.png">

**Comment by aroltsch** [comment]
@amprokop can you please clarify what is needed for this to pass validation. Thanks!

**Comment by amprokop** [comment]
@kierachell @aroltsch — Artem's comment above will be resolved by https://github.com/department-of-veterans-affairs/caseflow/issues/2312.

**Comment by kierachell** [comment]
**PASSED**
issues addressed by the comments above
