### ISSUE TITLE
Confirm Case Details | How to handle missing BGS POA data

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2256]
# Description
When attempting to Certify an Appeal,
and BGS returns `no POA found` or throws `incorrect participant id` error,
no useful information is displayed in Caseflow,
and `nil` values are saved in DB if user says that VBMS data is correct.

## Reproduction Steps

**Scenario 1 -**

1. Go to Certify an appeal
1. on Confirm Case Details page get blank values from BGS
1. Select that VBMS is correct
1. Attempt to finish Certification
1. Get System Error

**Validated in the following Envrionment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [ ] Prod

## Logs:

- No POA found
```
rO0ABXdUAB13ZWJsb2dpYy5hcHAuQ29ycG9yYXRlRGF0YUVBUgAAANYAAAAjd2VibG9naWMud29ya2FyZWEuU3RyaW5nV29ya0NvbnRleHQABjEwLjIuMAAA</work:WorkContext></S:Header><S:Body><ns2:findPOAsByFileNumbersResponse xmlns:ns2="http://org.services.vetsnet.vba.va.gov/"><return><fileNumber>516517678</fileNumber><message>No POA found for 600161052</message><ptcpntId>600161052</ptcpntId></return></ns2:findPOAsByFileNumbersResponse></S:Body></S:Envelope>
```

- Participant ID error:
```
Savon::SOAPFault: (S:Server) AddressWebService-->findPtcpntAddrs-->findPersonByPtcpntId-->No Person found for ptcpnt_id 600156025
```

- Validation error
```
Caseflow::Error::CertificationMissingData (Caseflow::Error::CertificationMissingData): 
app/controllers/certifications_controller.rb:105:in `validate_data_presence_v2'                                                                                                                                                            
app/controllers/certifications_controller.rb:50:in `certify_v2'                                                                                                                                                                            app/middleware/metrics_collector.rb:14:in `call'                                                                                                                                                                                           
app/middleware/metrics_auth.rb:10:in `call'
```

## Sentry:

https://10.236.66.249/sentry/caseflow-uat/issues/239/events/

## Screenshots
**_Scenario 1 - [No VBMS info]_**
<img width="1003" alt="screen shot 2017-06-06 at 2 17 13 pm" src="https://user-images.githubusercontent.com/18075411/26846100-be5ba1d6-4ac6-11e7-8b41-b2309b418fa9.png">

**Comment by kierachell** [comment]
## Steps:
1. With a VBMS POA data missing
1. On Confirm Case Details say VBMS is correct

It tries to save
```
Certification Load (1.9ms)  SELECT  "certifications".* FROM "certifications" LEFT OUTER JOIN certification_cancellations ON                                                                                   certifications.id = certification_cancellations.certification_id WHERE "certification_cancellations"."certification_id" IS 
NULL AND "certifications"."vacols_id" = $1 LIMIT 1  [["vacols_id", "2692779"]]                          dsva-
appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-
0f8961fc1a5505ad7-172.30.71.166 [appeals.cf.uat.ds.va.gov] [22d7f91a-0eaf-4da7-a4ec-
b2851d13f2d4] [172.30.71.166] [CASEFLOW_317   caseflow@va.gov] [2017-06-09 10:42:29 -0400]    
(1.5ms)  BEGIN                                                                                                                                                                                       
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0f8961fc1a5505ad7-172.30.71.166 [appeals.cf.uat.ds.va.gov] [22d7f91a-0eaf-4da7-a4ec-
b2851d13f2d4] [172.30.71.166] [CASEFLOW_317   caseflow@va.gov] [2017-06-09 10:42:29 -0400]   
SQL (1.6ms)  UPDATE "certifications" SET "certifying_official_name" = $1, "certifying_official_title" = 
$2, "updated_at" = $3 WHERE "certifications"."id" = $4  [["certifying_official_name", "asdasdasd"], 
["certifying_official_title", "RATING_SPECIALIST"], ["updated_at", "2017-06-09 14:42:29.454817"], 
["id", 10470]]                                                                                                                     dsva-appeals-
certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0f8961fc1a5505ad7-
172.30.71.166 [appeals.cf.uat.ds.va.gov] [22d7f91a-0eaf-4da7-a4ec-b2851d13f2d4] [172.30.71.166] 
[CASEFLOW_317   caseflow@va.gov] [2017-06-09 10:42:29 -0400]    (4.2ms)  COMMIT                                                                                                                                                                                      
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-
0f8961fc1a5505ad7-172.30.71.166 [appeals.cf.uat.ds.va.gov] [22d7f91a-0eaf-4da7-a4ec-
b2851d13f2d4] [172.30.71.166] [CASEFLOW_317   caseflow@va.gov] [2017-06-09 10:42:29 -0400]   
Form8 Load (1.9ms)  SELECT  "form8s".* FROM "form8s" WHERE "form8s"."certification_id" = $1 LIMIT 
1  [["certification_id", 10470]]                                                                    dsva-appeals-certification-
uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0f8961fc1a5505ad7-172.30.71.166 
[appeals.cf.uat.ds.va.gov] [22d7f91a-0eaf-4da7-a4ec-b2851d13f2d4] [172.30.71.166] 
[CASEFLOW_317   caseflow@va.gov] [2017-06-09 10:42:29 -0400]    (1.4ms)  BEGIN                                                                                                                                                                                       
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-
0f8961fc1a5505ad7-172.30.71.166 [appeals.cf.uat.ds.va.gov] [22d7f91a-0eaf-4da7-a4ec-
b2851d13f2d4] [172.30.71.166] [CASEFLOW_317   caseflow@va.gov] [2017-06-09 10:42:29 -0400]   
SQL (1.7ms)  UPDATE "form8s" SET "representative_type" = $1, "representative_name" = $2, 
"hearing_preference" = $3, "certifying_official_name" = $4, "certifying_official_title" = $5, "updated_at" 
=$6 WHERE "form8s"."id" = $7  [["representative_type", nil], ["representative_name", nil], 
["hearing_preference", "HEARING_TYPE_NOT_SPECIFIED"], ["certifying_official_name", "asdasdasd"], 
["certifying_official_title", "RATING_SPECIALIST"], ["updated_at", "2017-06-09 14:42:29.468088"], 
["id", 11014]]                                                                                                                                                                           
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-
0f8961fc1a5505ad7-172.30.71.166 [appeals.cf.uat.ds.va.gov] [22d7f91a-0eaf-4da7-a4ec-
b2851d13f2d4] [172.30.71.166] [CASEFLOW_317   caseflow@va.gov] [2017-06-09 10:42:29 -0400]    
(4.0ms)  COMMIT                                                                                                                                                                                      
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-
0f8961fc1a5505ad7-172.30.71.166 172.30.66.175 - dsva [09/Jun/2017:10:42:29 -0400] "GET 
/metrics HTTP/1.0" 200 - 0.0114                      dsva-appeals-certification-uat/opt/caseflow-
certification/src/log/caseflow-certification.out i-09446c9981be6faaf-172.30.66.19 172.30.66.175 - 
dsva [09/Jun/2017:10:42:31 -0400] "GET /metrics HTTP/1.0" 200 - 0.0222                       dsva-
appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-
0f8961fc1a5505ad7-172.30.71.166 [appeals.cf.uat.ds.va.gov] [22d7f91a-0eaf-4da7-a4ec-
b2851d13f2d4] [172.30.71.166] [CASEFLOW_317   caseflow@va.gov] [2017-06-09 10:42:32 -0400] 
Completed 500 Internal Server Error in 3238ms (ActiveRecord: 22.8ms)                                                                                                                                    
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-
0f8961fc1a5505ad7-172.30.71.166 [appeals.cf.uat.ds.va.gov] [22d7f91a-0eaf-4da7-a4ec-
b2851d13f2d4] [172.30.71.166] [CASEFLOW_317   caseflow@va.gov] [2017-06-09 10:42:32 -0400]

dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-
0f8961fc1a5505ad7-172.30.71.166 TypeError (no implicit conversion of nil into String):                                                        
app/services/form8_pdf_service.rb:151:in `+'                                                                                                                                                                                               
app/services/form8_pdf_service.rb:151:in `block in pdf_values_for'                                                                                                                                                                         
app/services/form8_pdf_service.rb:129:in `each'                                                                                                                                                                                            
app/services/form8_pdf_service.rb:129:in `each_with_object'                                                                                                                                                                                
app/services/form8_pdf_service.rb:129:in `pdf_values_for'                                                                                                                                                                                  
app/services/form8_pdf_service.rb:167:in `save_pdf_for!'                                                                                                                                                                                   
app/models/form8.rb:46:in `save_pdf!'                                                                                                                                                                                                      app/controllers/certifications_controller.rb:60:in `certify_v2'
  app/middleware/metrics_collector.rb:14:in `call'                                                                                                                                                                                          app/middleware/metrics_auth.rb:10:in `call'
```

**Comment by kierachell** [comment]
**PASSED**

this error was finally fixed after a prod issue
