### ISSUE TITLE
[v2] Make sure representativeType and representativeName values are stored in form8 upon certifying

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow#2287]
Currently in v2, if we pick 'No' for 'Does the representative information from VBMS and VACOLS match?' and 'VBMS' for 'Which information source shows the correct representative for this appeal?', 
it will not update form8 with representativeName and representativeType values upon certifying.
Example:
 
![poa-info](https://user-images.githubusercontent.com/4960030/26943197-b7ee964a-4c52-11e7-9418-42a87ceb9a2f.gif)

**Comment by kierachell** [comment]
Currently failing:

```
UPDATE "form8s" SET "representative_type" = $1, "representative_name" = $2, "hearing_preference" = $3, "certifying_official_name" = $4, "certifying_official_title" = $5, "updated_at" = $6 WHERE "form8s"."id" = $7  [["representative_type", nil], ["representative_name", nil], ["hearing_preference", "HEARING_TYPE_NOT_SPECIFIED"], ["certifying_official_name", "RO49"], ["certifying_official_title", "OTHER"], ["updated_at", "2017-06-11 16:15:34.452016"], ["id", 11037]]
TypeError (no implicit conversion of nil into String):
  app/services/form8_pdf_service.rb:151:in `+'                                                                                                                                                                                               app/services/form8_pdf_service.rb:151:in `block in pdf_values_for'
  app/services/form8_pdf_service.rb:129:in `each'                                                                                                                                                                                            app/services/form8_pdf_service.rb:129:in `each_with_object'                                                                                                                                                                                app/services/form8_pdf_service.rb:129:in `pdf_values_for'
  app/services/form8_pdf_service.rb:167:in `save_pdf_for!'                                                                                                                                                                                   app/models/form8.rb:46:in `save_pdf!'
  app/controllers/certifications_controller.rb:60:in `certify_v2'                                                                                                                                                                            app/middleware/metrics_collector.rb:14:in `call'
  app/middleware/metrics_auth.rb:10:in `call'
```

**Comment by kierachell** [comment]
**PASSED**

seems to be form8 v2 specific
