### ISSUE TITLE
BGS Service | Handle `No BIRLS record found` error

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2297]
# Description
Apparently sometimes there might not be a BIRLS record for when we `fetch_veteran_info`,
and the user gets stuck on that Task and is unable to move on.

## Reproduction Steps

**Scenario 1 -**

1. Go to Dispatch
1. Get a veteran that has no BIRLS record
1. Try to process his claim
1. Fail
1. Get stuck

**Validated in the following Envrionment(s)**
- [ ] Dev
- [ ] UAT
- [ ] Preprod
- [X] Prod

## Logs:

- PARTIAL BGS Output
```
<?xml version='1.0' encoding='UTF-8'?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><ns2:findVeteranByFileNumberResponse 
xmlns:ns2="http://services.share.benefits.vba.va.gov/"><return><vetBirlsRecord>
<RETURN_CODE>BPNQ0100</RETURN_CODE><RETURN_MESSAGE>No BIRLS record 
found</RETURN_MESSAGE><SPACE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:nil="true"/><CLAIM_NUMBER xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:nil="true"/><SOC_SEC_NUMBER xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:nil="true"/><INS_PREFIX xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<INS_NUMBER xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/><LAST_NAME 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/><FIRST_NAME 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/><MIDDLE_NAME 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/><NAME_SUFFIX 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/><BIRTH_MONTH 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/><BIRTH_DAY 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/><BIRTH_CENTURY 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/><BIRTH_YEAR 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/><DATE_OF_BIRTH 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/><DEATH_MONTH 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/><DEATH_DAY 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/><DEATH_CENTURY 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/><DEATH_YEAR 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/><DATE_OF_DEATH 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/><POW_NUMBER_OF_DAYS 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<TOTAL_ACTIVE_SERVICE_YEARS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:nil="true"/><TOTAL_ACTIVE_SERVICE_MONTHS xmlns:xsi="http://www.w3.org/2001/XMLSchema-
instance" xsi:nil="true"/><TOTAL_ACTIVE_SERVICE_DAYS xmlns:xsi="http://www.w3.org
/2001/XMLSchema-instance" xsi:nil="true"/><DISABILITY_SEVERANCE_PAY 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<LUMP_SUM_READJUSTMENT_PAY xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>...............
```

- Our Code Error:
```
</ns2:findVeteranByFileNumberResponse></S:Body></S:Envelope>
NoMethodError: undefined method `merge' for nil:NilClass
        from /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/bundler/gems/ruby-bgs-b84a5baba28a/lib/bgs/services/veteran.rb:22:in `find_by_file_number'
        from /opt/caseflow-certification/src/app/services/external_api/bgs_service.rb:38:in `block in fetch_veteran_info'
        from /opt/caseflow-certification/src/app/services/metrics_service.rb:12:in `block in record'
        from /opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/benchmark.rb:288:in `measure'
        from /opt/caseflow-certification/src/app/services/metrics_service.rb:11:in `record'
        from /opt/caseflow-certification/src/app/services/external_api/bgs_service.rb:35:in `fetch_veteran_info'
        from (irb):25
        from /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/commands/console.rb:110:in `start'
        from /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
        from /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:9:in `require'
        from bin/rails:9:in `<main>'
```

## Sentry:

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/208/

# Related Issues
**_Support_**
https://github.com/department-of-veterans-affairs/appeals-support/issues/183
https://github.com/department-of-veterans-affairs/appeals-support/issues/182

**Comment by joofsh** [comment]
@kierachell What do you mean by the user gets stuck? If this is before EP creation they should be able to cancel still, right?

**Comment by kierachell** [comment]
So... there's a fun case when an `Error` banner shows up the `Cancel` button will not be clickable - as in, I click and it just does nothing. No JS errors or anything, I am forced to go back a page and cancel from there...

**Comment by kierachell** [comment]
**PASSED**

I dun think anyone cares
