### ISSUE TITLE
Investigate "no such file" stacktrace

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow#251]
```
F, [2016-04-19T08:06:50.638954 #51986] FATAL -- : [xxxxxx@va.gov (RO18)]
Errno::ENOENT (No such file or directory @ rb_sysopen - /opt/va.gov/caseflow/src/tmp/pdfs/form8-xxxx.pdf):
  app/services/appeal_repository.rb:85:in `block in send_and_log_request'
  app/services/metrics_service.rb:8:in `block in timer'
  /app/caseflow/.rbenv/versions/2.2.4/lib/ruby/2.2.0/benchmark.rb:288:in `measure'
  app/services/metrics_service.rb:7:in `timer'
  app/services/appeal_repository.rb:84:in `send_and_log_request'
  app/services/appeal_repository.rb:63:in `upload_form8_for'
  app/services/appeal_repository.rb:54:in `certify'
  app/models/appeal.rb:100:in `certify'
  app/models/appeal.rb:95:in `certify!'
```

**Comment by shanear** [comment]
fixed by #580, closing.
