### ISSUE TITLE
/health-check is passing even though demo env crashes

### ISSUE THREAD

**Issue by askldjd** [department-of-veterans-affairs/caseflow#2594]
Demo env was down in 20170712 04:05PM EST

All requests return 500s.
![image](https://user-images.githubusercontent.com/3258724/28137779-724a4118-671c-11e7-9bcc-a10e787c2a21.png)

`/health-check` returns 200
![image](https://user-images.githubusercontent.com/3258724/28137798-87f8c93a-671c-11e7-8b10-627a73f20073.png)

This shouldn't happen. `/health-check` should at least verify that the main page is up and running.
## Logs
```
dsva-appeals-certification-demo/opt/caseflow-certification/src/log/caseflow-certification.out i-0d1c21e52a575e4f6-172.30.65.212 [52.222.85.52] [e7a5f718-64a7-4f45-9b01-6f76ae3eb1e3] [localho
st] [2017-07-12 15:52:17 -0400] Completed 500 Internal Server Error in 5011ms (ActiveRecord: 0.0ms)                                                                                           
dsva-appeals-certification-demo/opt/caseflow-certification/src/log/caseflow-certification.out i-0d1c21e52a575e4f6-172.30.65.212 Error during failsafe response: could not obtain a database co
nnection within 5.000 seconds (waited 5.000 seconds)                                                                                                                                          
  /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:189:in `block in wait_poll'
  /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:180:in `loop'                          
  /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:180:in `wait_poll'                     
  /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:135:in `block in poll'                 
  /opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'                                                                                                                
  /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:145:in `synchronize'                   
  /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:133:in `poll'                          
  /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:425:in `acquire_connection'            
  /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'             
  /opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'                                                                                                                
  /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'                      
  /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'           
  /opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'                                                                                                                
  /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'                    
  /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'           
  /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_handling.rb:113:in `retrieve_connection'                                    
  /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_handling.rb:87:in `connection'                                              
  /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:48:in `connection'                                              
  /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/relation/query_methods.rb:980:in `create_binds'                                        
  /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/relation/query_methods.rb:954:in `build_where'                                         
  /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/relation/query_methods.rb:584:in `where!'      
  /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/relation/query_methods.rb:574:in `where'                                               
  /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/relation/finder_methods.rb:84:in `find_by'
  /opt/caseflow-certification/src/app/models/user.rb:155:in `from_session'                                                                                                                    
  /opt/caseflow-certification/src/app/controllers/application_controller.rb:52:in `current_user'                                                                                              
  /opt/caseflow-certification/src/app/controllers/application_controller.rb:113:in `set_timezone'                                                                                             
 ```

**Comment by askldjd** [comment]
Closing this since this issue may no longer be relevant.
