### ISSUE TITLE
Refactor Certification backend to allow us to render v2 without VACOLS/VBMS calls having finished

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2668]

**Comment by kierachell** [comment]
Currently the job runs and seems to make VACOLS calls but then:
```
Performing StartCertificationJob from Sidekiq(default) with arguments: gid://caseflow-certification/Certification/10956
dsva-appeals-certification_worker-uat/opt/caseflow-certification/src/log/caseflow-certification-worker.out i-0e89b2cb27dc47dd9-172.30.70.152 [ActiveJob] [StartCertificationJob] [f4f9507c-abdc-4144-a8a6-e0
a5da0cb1b8] [2017-08-06 16:43:30 -0400]   Form8 Load (1.9ms)  SELECT  "form8s".* FROM "form8s" WHERE "form8s"."certification_id" = $1 LIMIT 1  [["certification_id", 10956]]
dsva-appeals-certification_worker-uat/opt/caseflow-certification/src/log/caseflow-certification-worker.out i-0e89b2cb27dc47dd9-172.30.70.152 [ActiveJob] [StartCertificationJob] [f4f9507c-abdc-4144-a8a6-e0a5da0cb1b8] [2017-08-06 16:43:30 -0400]    (1.5ms)  BEGIN
dsva-appeals-certification_worker-uat/opt/caseflow-certification/src/log/caseflow-certification-worker.out i-0e89b2cb27dc47dd9-172.30.70.152 [ActiveJob] [StartCertificationJob] [f4f9507c-abdc-4144-a8a6-e0a5da0cb1b8] [2017-08-06 16:43:30 -0400]    (1.5ms)  COMMIT
dsva-appeals-certification_worker-uat/opt/caseflow-certification/src/log/caseflow-certification-worker.out i-0e89b2cb27dc47dd9-172.30.70.152 [ActiveJob] [StartCertificationJob] [f4f9507c-abdc-4144-a8a6-e0a5da0cb1b8] [2017-08-06 16:43:30 -0400]   Appeal Load (1.7ms)  SELECT  "appeals".* FROM "appeals" WHERE "appeals"."vacols_id" = $1 LIMIT 1  [["vacols_id", "2599462"]]
dsva-appeals-certification_worker-uat/opt/caseflow-certification/src/log/caseflow-certification-worker.out i-0e89b2cb27dc47dd9-172.30.70.152 [ActiveJob] [StartCertificationJob] [f4f9507c-abdc-4144-a8a6-e0
a5da0cb1b8] [2017-08-06 16:43:30 -0400] STARTED VACOLS: load_vacols_data 2599462                                                                                                                            dsva-appeals-certification_worker-uat/opt/caseflow-certification/src/log/caseflow-certification-worker.out i-0e89b2cb27dc47dd9-172.30.70.152 [ActiveJob] [StartCertificationJob] [f4f9507c-abdc-4144-a8a6-e0
a5da0cb1b8] [2017-08-06 16:43:31 -0400]   VACOLS::Case Load (107.3ms)  SELECT  "VACOLS"."BRIEFF".* FROM "VACOLS"."BRIEFF" WHERE "VACOLS"."BRIEFF"."BFKEY" = :a1 AND ROWNUM <= 1   [["bfkey", "2599462"]]    dsva-appeals-certification_worker-uat/opt/caseflow-certification/src/log/caseflow-certification-worker.out i-0e89b2cb27dc47dd9-172.30.70.152 [ActiveJob] [StartCertificationJob] [f4f9507c-abdc-4144-a8a6-e0
a5da0cb1b8] [2017-08-06 16:43:31 -0400]   VACOLS::Folder Load (105.6ms)  SELECT "VACOLS"."FOLDER".* FROM "VACOLS"."FOLDER" WHERE "VACOLS"."FOLDER"."TICKNUM" IN ('2599462')                                 dsva-appeals-certification_worker-uat/opt/caseflow-certification/src/log/caseflow-certification-worker.out i-0e89b2cb27dc47dd9-172.30.70.152 [ActiveJob] [StartCertificationJob] [f4f9507c-abdc-4144-a8a6-e0
a5da0cb1b8] [2017-08-06 16:43:31 -0400]   VACOLS::Correspondent Load (105.7ms)  SELECT "VACOLS"."CORRES".* FROM "VACOLS"."CORRES" WHERE "VACOLS"."CORRES"."STAFKEY" IN ('CK779938')                         dsva-appeals-certification_worker-uat/opt/caseflow-certification/src/log/caseflow-certification-worker.out i-0e89b2cb27dc47dd9-172.30.70.152 [ActiveJob] [StartCertificationJob] [f4f9507c-abdc-4144-a8a6-e0
a5da0cb1b8] [2017-08-06 16:43:31 -0400] FINISHED VACOLS: load_vacols_data 2599462:   0.010000   0.000000   0.010000 (  1.863261)                                                                            dsva-appeals-certification_worker-uat/opt/caseflow-certification/src/log/caseflow-certification-worker.out i-0e89b2cb27dc47dd9-172.30.70.152 [ActiveJob] [StartCertificationJob] [f4f9507c-abdc-4144-a8a6-e0
a5da0cb1b8] [2017-08-06 16:43:31 -0400]    (1.6ms)  BEGIN                                                                                                                                                   dsva-appeals-certification_worker-uat/opt/caseflow-certification/src/log/caseflow-certification-worker.out i-0e89b2cb27dc47dd9-172.30.70.152 [ActiveJob] [StartCertificationJob] [f4f9507c-abdc-4144-a8a6-e0
a5da0cb1b8] [2017-08-06 16:43:31 -0400]    (1.6ms)  COMMIT                                                                                                                                                  dsva-appeals-certification_worker-uat/opt/caseflow-certification/src/log/caseflow-certification-worker.out i-0e89b2cb27dc47dd9-172.30.70.152 [ActiveJob] [StartCertificationJob] [f4f9507c-abdc-4144-a8a6-e0
a5da0cb1b8] [2017-08-06 16:43:31 -0400] StartCertificationJob failed                                                                                                                                        dsva-appeals-certification_worker-uat/opt/caseflow-certification/src/log/caseflow-certification-worker.out i-0e89b2cb27dc47dd9-172.30.70.152 [ActiveJob] [StartCertificationJob] [f4f9507c-abdc-4144-a8a6-e0
a5da0cb1b8] [2017-08-06 16:43:31 -0400]    (1.5ms)  BEGIN                                                                                                                                                   dsva-appeals-certification_worker-uat/opt/caseflow-certification/src/log/caseflow-certification-worker.out i-0e89b2cb27dc47dd9-172.30.70.152 [ActiveJob] [StartCertificationJob] [f4f9507c-abdc-4144-a8a6-e0
a5da0cb1b8] [2017-08-06 16:43:31 -0400]   SQL (1.7ms)  UPDATE "certifications" SET "loading_data" = $1, "loading_data_failed" = $2, "updated_at" = $3 WHERE "certifications"."id" = $4  [["loading_data", "f"], ["loading_data_failed", "t"], ["updated_at", "2017-08-06 20:43:31.958275"], ["id", 10956]]
dsva-appeals-certification_worker-uat/opt/caseflow-certification/src/log/caseflow-certification-worker.out i-0e89b2cb27dc47dd9-172.30.70.152 [ActiveJob] [StartCertificationJob] [f4f9507c-abdc-4144-a8a6-e0a5da0cb1b8] [2017-08-06 16:43:31 -0400]    (2.3ms)  COMMIT
dsva-appeals-certification_worker-uat/opt/caseflow-certification/src/log/caseflow-certification-worker.out i-0e89b2cb27dc47dd9-172.30.70.152 [ActiveJob] [StartCertificationJob] [f4f9507c-abdc-4144-a8a6-e0a5da0cb1b8] [2017-08-06 16:43:31 -0400] Performed StartCertificationJob from Sidekiq(default) in 1887.44ms
dsva-appeals-certification_worker-uat/opt/caseflow-certification/src/log/caseflow-certification-worker.out i-0e89b2cb27dc47dd9-172.30.70.152 [2017-08-06 16:43:31 -0400] done: 1.895 sec
```

- There's two jobs or? Why is it happy failing? :(
<img width="1123" alt="screen shot 2017-08-06 at 4 49 47 pm" src="https://user-images.githubusercontent.com/18075411/29006927-46086954-7ac7-11e7-890e-39726ae2ca32.png">

**Comment by kierachell** [comment]
### Method signature is different and `current_user` is still not passed to the job:
```
NameError (undefined local variable or method `current_user' for #<Certification:0x007fe9cc507950>):
  app/models/certification.rb:23:in `async_start!'                                                                                                                                                            app/controllers/certifications_controller.rb:6:in `new'
  app/middleware/metrics_collector.rb:14:in `call'                                                                                                                                                            app/middleware/metrics_auth.rb:10:in `call'
```

- Where is current user coming from?
```
if Rails.env.development? || Rails.env.test?
      StartCertificationJob.perform_now(self)
    else
      StartCertificationJob.perform_later(self, current_user)
    end
```

**Comment by kierachell** [comment]
**PASSED**
whew....
<img width="1131" alt="screen shot 2017-08-08 at 6 53 15 pm" src="https://user-images.githubusercontent.com/18075411/29099529-f2f9af26-7c73-11e7-8c35-7d4e5db30e8b.png">
