### ISSUE TITLE
Case Assignments | Previously created Appeals "reinserted" on CaseAssignments load?

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2804]
# Description
When going to Case Assignments page (aka Welcome Gate) it seems like Appeals already in our DB are "reinserted" in certain cases

Potentially related to https://github.com/department-of-veterans-affairs/caseflow/issues/2769

## Reproduction Steps

**Scenario 1 -**

1. Go to `/reader/appeal` aka Welcome Gate aka Case Assignments
1. Observe you get "Welcome gate cannot be loaded" page
1. Reload page
1. Move on with your day

**Validated in the following Environment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [ ] Prod

## Logs:
```
INSERT INTO "appeals" ("vacols_id", "vbms_id", "private_attorney_or_agent") VALUES ($1, $2, $3) RETURNING "id"[0m  [["vacols_id", "2597097"], ["vbms_id", "097337285S"], ["private_attorney_or_agent", "t"]]
[[0m [36mi-0457b6b0f5953062a-172.30.67.42[0m [appeals.cf.uat.ds.va.gov] [266604eb-e9cb-489c-905f-85691c797fc4] [172.30.67.42] [CF_SCOTTY_317   caseflow@va.gov] [2017-08-02 20:18:40 -0400]   [1m[35m (0.4ms)[0m  ROLLBACK
[[0m [36mi-0457b6b0f5953062a-172.30.67.42[0m [appeals.cf.uat.ds.va.gov] [266604eb-e9cb-489c-905f-85691c797fc4] [172.30.67.42] [CF_SCOTTY_317   caseflow@va.gov] [2017-08-02 20:18:40 -0400] Completed 500 Internal Server Error in 9182ms (ActiveRecord: 5557.9ms)
[[0m [36mi-0457b6b0f5953062a-172.30.67.42[0m [appeals.cf.uat.ds.va.gov] [266604eb-e9cb-489c-905f-85691c797fc4] [172.30.67.42] [CF_SCOTTY_317   caseflow@va.gov] [2017-08-02 20:18:40 -0400]
[[0m [36mi-0457b6b0f5953062a-172.30.67.42[0m ActiveRecord::RecordNotUnique (PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_appeals_on_vacols_id"
[[0m [36mi-0457b6b0f5953062a-172.30.67.42[0m DETAIL:  Key (vacols_id)=(2597097) already exists.
[[0m [36mi-0457b6b0f5953062a-172.30.67.42[0m : INSERT INTO "appeals" ("vacols_id", "vbms_id", "private_attorney_or_agent") VALUES ($1, $2, $3) RETURNING "id"):
  app/models/appeal.rb:98:in `vbms_id'
  app/models/appeal.rb:375:in `to_hash'
  app/models/user.rb:115:in `block in current_case_assignments_with_views'
  app/models/user.rb:114:in `map'
  app/models/user.rb:114:in `current_case_assignments_with_views'
  app/controllers/reader/appeal_controller.rb:8:in `block (3 levels) in index'
  app/services/metrics_service.rb:12:in `block in record'
  app/services/metrics_service.rb:11:in `record'
  app/controllers/reader/appeal_controller.rb:6:in `block (2 levels) in index'
  app/controllers/reader/appeal_controller.rb:3:in `index'
  app/middleware/metrics_collector.rb:14:in `call'
  app/middleware/metrics_auth.rb:10:in `call'
```

## Sentry:
https://sentry.uat.ds.va.gov/sentry/caseflow-uat/issues/351/

**_Engineering_**
https://github.com/department-of-veterans-affairs/caseflow/issues/2774

**Comment by kierachell** [comment]
**PASSED**
that was easy :D
<img width="452" alt="screen shot 2017-08-08 at 7 56 41 pm" src="https://user-images.githubusercontent.com/18075411/29099491-bead9840-7c73-11e7-939b-a157de75305e.png">
