### ISSUE TITLE
Brakeman complains about Nokogiri and Nokogiri breaks Caseflow

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3376]
as seen in: https://github.com/department-of-veterans-affairs/caseflow/pull/3338
Nokogiri needs to be updated in `connect_vbms` repo, but then it breaks Caseflow bootup:

- upon deploying this branch to uat :(

I dunno which gem update broke it :(
I suspect `activerecord-oracle_enhanced-adapter (1.6.9)`

```
LoadError: cannot load such file -- prometheus/client/rack/collector          
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1
/lib/active_support/dependencies.rb:274:in `require'                                                                   
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1
/lib/active_support/dependencies.rb:274:in `block in require'                                                          
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1
/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
config.ru:5:in `block in <main>'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/rack-1.6.8/lib/rack/builder.rb:55:in `instance_eval'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/rack-1.6.8/lib/rack/builder.rb:55:in `initialize'
  config.ru:in `new'
  config.ru:in `<main>'                                                                                                                                                                                     
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/rack-1.6.8/lib/rack/builder.rb:49:in `eval'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/rack-1.6.8/lib/rack/builder.rb:49:in `new_from_string'                                                                                      /opt/caseflow-certification
/src/vendor/bundle/ruby/2.2.0/gems/rack-1.6.8/lib/rack/builder.rb:40:in `parse_file'                                                                                           
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/puma-2.16.0/lib/puma
/configuration.rb:155:in `load_rackup'                                                                                  
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/puma-2.16.0/lib/puma
/configuration.rb:99:in `app'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/puma-2.16.0/lib/pum
/runner.rb:114:in `load_and_bind'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/puma-2.16.0/lib/puma/single.rb:79:in `run'                                                                                                  
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/puma-2.16.0/lib/puma/cli.rb:214:in `run'                                                                                                    
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/puma-2.16.0/bin/puma:10:in `<top (required)>'                                                                                               
/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/bin/puma:23:in `load'                                                                                                                            /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/bin/puma:23:in `<top (required)>'
```

**Comment by amprokop** [comment]
https://github.com/department-of-veterans-affairs/caseflow/pull/3378
