### ISSUE TITLE
Cleanup Sidekiq references

### ISSUE THREAD

**Issue by sunil-sadasivan** [department-of-veterans-affairs/caseflow#3426]
We no longer use sidekiq.  Instead we use shoryuken and SQS.  After some certainty of confidence this works well, let's remove all references to sidekiq to remove confusion. 

**AC**
Ensure the app functionality works as expected.  
Specifically test the StartCertificationJob.  (/certifications/ routes)

**Comment by kierachell** [comment]
### Metrics collector still looks for sidekiq:
```
2017-10-19 07:58:50 -0400: Rack app error: #<NameError: uninitialized constan
t MetricsCollector::Sidekiq>                                                                                                                                                                                dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-02476a75d1e178d8f-172.30.67.123 /opt/caseflow-certification/src/app/middleware/metrics_collector.rb:49:in `co
llect_background_jobs_metrics'                                                                                                                                                                              dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-02476a75d1e178d8f-172.30.67.123 /opt/caseflow-certification/src/app/middleware/metrics_collector.rb:22:in `pe
rform'                                                                                                                                                                                                      dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-02476a75d1e178d8f-172.30.67.123 /opt/caseflow-certification/src/app/middleware/metrics_collector.rb:12:in `ca
ll'                                                                                                                                                                                                         dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-02476a75d1e178d8f-172.30.67.123 /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/rack-1.6.8/lib/
rack/deflater.rb:35:in `call'                                                                                                                                                                               dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-02476a75d1e178d8f-172.30.67.123 /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/rack-1.6.8/lib/
rack/auth/basic.rb:25:in `call'                                                                                                                                                                             dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-02476a75d1e178d8f-172.30.67.123 /opt/caseflow-certification/src/app/middleware/metrics_auth.rb:8:in `call'
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-02476a75d1e178d8f-172.30.67.123 /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/puma-2.16.0/lib/puma/configuration.rb:81:in `call'
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-02476a75d1e178d8f-172.30.67.123 /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/puma-2.16.0/lib/puma/server.rb:557:in `handle_request'
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-02476a75d1e178d8f-172.30.67.123 /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/puma-2.16.0/lib/puma/server.rb:404:in `process_client'
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-02476a75d1e178d8f-172.30.67.123 /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/puma-2.16.0/lib/puma/server.rb:270:in `block in run'
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-02476a75d1e178d8f-172.30.67.123 /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/puma-2.16.0/lib/puma/thread_pool.rb:106:in `call'
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-02476a75d1e178d8f-172.30.67.123 /opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/puma-2.16.0/lib/puma/thread_pool.rb:106:in `block in spawn_thread'
```

**Comment by sunil-sadasivan** [comment]
Ah good catch @kierachell!  Taking a look now

**Comment by kierachell** [comment]
**PASSED**

No more errors, so uh.. yeah... dunno what to `not` show
