### ISSUE TITLE
Add admin page for viewing "stuck" appeals in Dispatch

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#3525]
At times we have appeals that get stuck in Dispatch because of several reasons:
- Sensitivity level is too high
- Appeal is connected to a Veteran that works at AMC
- No "person" record in BGS

When this happens, we need to highlight these cases to a manager at AMC and allow them to invalidate the cases and work them outside of Caseflow Dispatch

### AC
- In an admin view, show the 10 oldest unassigned appeals

**Comment by kierachell** [comment]
### Currently just kinda hangs if it encounters errors:
```
Appeal Load (1.7ms)  SELECT  "appeals".* FROM "appeals" WHERE "appeals"."id" = $1 LIMIT 1  [["id", 15935]]
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0f398379dffaa1b8b-172.30.71.223 [appeals.cf.uat.ds.va.gov] [f3246807-46b9-4259-a0d3-501605a0379f] [172.30.71.223] [CASEFLOW_317   caseflow@va.gov] [2017-10-25 19:13:29 -0400] Completed 500 Internal Server Error in 51ms (ActiveRecord: 18.7ms)
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0f398379dffaa1b8b-172.30.71.223 [appeals.cf.uat.ds.va.gov] [f3246807-46b9-4259-a0d3-501605a0379f] [172.30.71.223] [CASEFLOW_317   caseflow@va.gov] [2017-10-25 19:13:29 -0400]
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0f398379dffaa1b8b-172.30.71.223 NoMethodError (undefined method `decision_type' for nil:NilClass):             app/models/tasks/establish_claim.rb:20:in `block in <class:EstablishClaim>'
  app/models/concerns/cached_attributes.rb:41:in `instance_eval'                                                                                                                                              app/models/concerns/cached_attributes.rb:41:in `block in cache_attribute'
  app/models/tasks/establish_claim.rb:36:in `to_hash'                                                                                                                                                         app/controllers/tasks_controller.rb:21:in `index'
  app/middleware/metrics_collector.rb:14:in `call'                                                                                                                                                            app/middleware/metrics_auth.rb:10:in `call'
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0f398379dffaa1b8b-172.30.71.223 [appeals.cf.uat.ds.va.gov] [f3246807-46b9-4259-a0d3-501605a0379f] [172.30.71.223] [CASEFLOW_317   caseflow@va.gov] [2017-10-25 19:13:29 -0400] Processing by ErrorsController#show as JSON
dsva-appeals-certification-uat/opt/caseflow-certification/src/log/caseflow-certification.out i-0f398379dffaa1b8b-172.30.71.223 [appeals.cf.uat.ds.va.gov] [f3246807-46b9-4259-a0d3-501605a0379f] [172.30.71.223] [CASEFLOW_317   caseflow@va.gov] [2017-10-25 19:13:29 -0400]   Parameters: {"task"=>{}, "state"=>"unassigned", "type"=>"EstablishClaim", "status_code"=>"500", "error"=>{"task"=>{}}}
```

- Granted, I made this error happen; but at least it should show a `500`

**Comment by sunil-sadasivan** [comment]
Adding this back to validation for some more information on how to reproduce the hang.  Unable to reproduce this locally @kierachell.  Eager to pair on this too!

**Comment by kierachell** [comment]
**PASSED**

Haven't been able to reproduce it recently.
