### ISSUE TITLE
Missing asset - /caseflow/img/arrow-down.svg

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/caseflow#599]
```
I, [2015-12-02T08:43:38.411000 #61702]  INFO -- : Started GET "/caseflow/img/arrow-down.svg" for 127.0.0.1 at 2015-12-02 08:43:38 -0600
F, [2015-12-02T08:43:38.476000 #61702] FATAL -- :
ActionController::RoutingError (No route matches [GET] "/caseflow/img/arrow-down.svg"):
  vendor/bundle/jruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  vendor/bundle/jruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/jruby/2.2.0/gems/railties-4.2.4/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/jruby/2.2.0/gems/railties-4.2.4/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/jruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/jruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/jruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/jruby/2.2.0/gems/railties-4.2.4/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/jruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/jruby/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
  vendor/bundle/jruby/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
  vendor/bundle/jruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  vendor/bundle/jruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/static.rb:116:in `call'
  vendor/bundle/jruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
  vendor/bundle/jruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/ssl.rb:24:in `call'
  vendor/bundle/jruby/2.2.0/gems/railties-4.2.4/lib/rails/engine.rb:518:in `call'
  vendor/bundle/jruby/2.2.0/gems/railties-4.2.4/lib/rails/application.rb:165:in `call'
  vendor/bundle/jruby/2.2.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
  vendor/bundle/jruby/2.2.0/gems/puma-2.15.3-java/lib/puma/server.rb:541:in `handle_request'
  vendor/bundle/jruby/2.2.0/gems/puma-2.15.3-java/lib/puma/server.rb:388:in `process_client'
  vendor/bundle/jruby/2.2.0/gems/puma-2.15.3-java/lib/puma/server.rb:270:in `block in run'
  org/jruby/RubyProc.java:318:in `call'
  vendor/bundle/jruby/2.2.0/gems/puma-2.15.3-java/lib/puma/thread_pool.rb:106:in `block in spawn_thread'


I, [2015-12-02T08:43:38.480000 #61702]  INFO -- : Processing by WebController#http_404_not_found as HTML
I, [2015-12-02T08:43:38.480000 #61702]  INFO -- :   Parameters: {"code"=>404}
I, [2015-12-02T08:43:38.488000 #61702]  INFO -- :   Rendered web/404.html.erb within layouts/basic (1.0ms)
I, [2015-12-02T08:43:38.496000 #61702]  INFO -- : Completed 404 Not Found in 14ms (Views: 9.1ms | ActiveRecord: 0.0ms)
```

**Comment by paultag** [comment]
```
./app/assets/stylesheets/application.css.scss:        background: url(asset-path('icons/arrow-down.svg')) 50% 100% no-repeat;
```

Seems to be a sensible path, but the rest appear to be `img/arrow-down`, rather than `icons`, and it's also missing `asset-path`. I'm guessing this is likely why.

```
./app/assets/stylesheets/_scss/elements/_inputs.scss:  background-image: url('../img/arrow-down.png');
./app/assets/stylesheets/_scss/elements/_inputs.scss:  background-image: url('../img/arrow-down.svg');
./app/assets/stylesheets/_scss/components/_footer.scss:      background-image: url('../img/arrow-down.png');
./app/assets/stylesheets/_scss/components/_footer.scss:      background-image: url('../img/arrow-down.svg');
```

**Comment by paultag** [comment]
(But I don't know the asset pipeline at all. Paging @shanear )

**Comment by orischwartz** [comment]
I just hit this same issue in certifications project. I believe there was a change to USWDS and the asset is now at `assets/arrow-down.svg`. We'll need to update our scss file.
