### ISSUE TITLE
AMA Decisions | Sync dispositions for AMA higher level reviews and supplemental claims

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#6186]
As part of our end product sync job, we should also be syncing the dispositions for the contentions on those end products

## Acceptance Criteria
- When an end product is being synced with VBMS, if the EP is in cleared status "CLR", and the EP is for an AMA higher level review or supplemental claim and the dispositions for that EP haven't already been recorded, then the system syncs the dispositions for each of the issues on that HLR or SC by querying the dispositions for the associated contentions.
- If one or more of the dispositions does not exist, then an error should be raised. We should always have a disposition for each contention.

## Additional Notes
If a disposition is a DTA error, then this will eventually trigger the creation of a supplemental claim. This will be handled by the following story
blocks #6167

## Validation
True validation for this story is going to be fairly tricky, since we need the claim to go through the entire rating and awards process to get cleared and have dispositions. I think we should validate all of the decisions stories at one time with Mary Kate or Colin

- Validate that this works for comp & non-comp

**Comment by kahlouie** [comment]
Edit: This issue assumed that we were already syncing Claim Reviews, which we weren't. We now need to move sync job to end product establishments table.
This is also changing the way we sync ramp election eps.

Then we can find the source, if it's a claim review, sync the disposition. Don't worry about error handling yet.

**Comment by shanear** [comment]
Validating this with the following EP:

```
EndProductEstablishment.find_by(veteran_file_number: "123458311", modifier: "032")
```

**Comment by shanear** [comment]
This is blowing up 😢

```
[2018-10-04 13:52:42 -0400] STARTED sent VBMS request VBMS::Requests::GetDispositions for 600138634
[2018-10-04 13:52:43 -0400] FINISHED sent VBMS request VBMS::Requests::GetDispositions for 600138634:   0.018987   0.000308   0.019295 (  0.449921)

[2018-10-04 13:52:43 -0400]    (1.6ms)  ROLLBACK
Traceback (most recent call last):
       10: from (irb):9
        9: from app/models/end_product_establishment.rb:145:in `sync!'
        8: from app/models/end_product_establishment.rb:151:in `block in sync!'
        7: from app/models/end_product_establishment.rb:300:in `sync_source!'
        6: from app/models/higher_level_review.rb:52:in `on_sync'
        5: from app/models/claim_review.rb:73:in `on_sync'
        4: from app/models/higher_level_review.rb:92:in `sync_dispositions'
        3: from app/models/claim_review.rb:91:in `sync_dispositions'
        2: from app/models/claim_review.rb:91:in `each'
        1: from app/models/claim_review.rb:92:in `block in sync_dispositions'
EndProductEstablishment::BGSSyncError (undefined method `[]' for #<VBMS::Responses::Disposition:0x0000562a1b8ebe58>)
```

**Comment by shanear** [comment]
more blowing up:
```
Traceback (most recent call last):
       11: from (irb):13
       10: from app/models/end_product_establishment.rb:145:in `sync!'
        9: from app/models/end_product_establishment.rb:151:in `block in sync!'
        8: from app/models/end_product_establishment.rb:300:in `sync_source!'
        7: from app/models/higher_level_review.rb:52:in `on_sync'
        6: from app/models/claim_review.rb:73:in `on_sync'
        5: from app/models/higher_level_review.rb:92:in `sync_dispositions'
        4: from app/models/claim_review.rb:91:in `sync_dispositions'
        3: from app/models/claim_review.rb:91:in `each'
        2: from app/models/claim_review.rb:92:in `block in sync_dispositions'
        1: from app/models/claim_review.rb:105:in `matching_request_issue'
EndProductEstablishment::BGSSyncError (Couldn't find RequestIssue)
```

**Comment by shanear** [comment]
Making this request to Colin for some new UAT test datas

File Number: 123458316
031 - Higher-Level Review Rating
DTA Error - Fed Recs: Service connection for Back is denied.
DTA Error - PMRs: Service connection for PTSD is granted with an evaluation of 30 percent effective October 1, 2017.

040 - Supplemental Claim Rating
Granted: Service connection for Back is denied.
Denied: Service connection for PTSD is granted with an evaluation of 30 percent effective October 1, 2017.

**Comment by shanear** [comment]
```
irb(main):004:0> EndProductEstablishment.where(veteran_file_number: "123458316", modifier: "031").first.source.request_issues
[2018-10-10 12:49:04 -0400]   EndProductEstablishment Load (1.0ms)  SELECT  "end_product_establishments".* FROM "end_product_establishments" WHERE "end_product_establishments"."veteran_file_number" = $1 AND "end_product_establishments"."modifier" = $2 ORDER BY "end_product_establishments"."id" ASC LIMIT $3  [["veteran_file_number", "123458316"], ["modifier", "031"], ["LIMIT", 1]]
[2018-10-10 12:49:04 -0400]   HigherLevelReview Load (0.5ms)  SELECT  "higher_level_reviews".* FROM "higher_level_reviews" WHERE "higher_level_reviews"."id" = $1 LIMIT $2  [["id", 253], ["LIMIT", 1]]
[2018-10-10 12:49:04 -0400]   RequestIssue Load (0.8ms)  SELECT  "request_issues".* FROM "request_issues" WHERE "request_issues"."review_request_id" = $1 AND "request_issues"."review_request_type" = $2 LIMIT $3  [["review_request_id", 253], ["review_request_type", "HigherLevelReview"], ["LIMIT", 11]]
=> #<ActiveRecord::Associations::CollectionProxy [#<RequestIssue id: 315, review_request_type: "HigherLevelReview", review_request_id: 253, rating_issue_reference_id: "114214", rating_issue_profile_date: "2018-07-30 11:37:35", contention_reference_id: "307986", description: "Service connection for Back is denied.", issue_category: nil, decision_date: nil, disposition: "DTA Error - Fed Recs", end_product_establishment_id: 167, removed_at: nil, rating_issue_associated_at: "2018-10-09 20:07:09", parent_request_issue_id: nil, notes: nil>, #<RequestIssue id: 314, review_request_type: "HigherLevelReview", review_request_id: 253, rating_issue_reference_id: "114213", rating_issue_profile_date: "2018-07-30 11:37:35", contention_reference_id: "307987", description: "Service connection for PTSD is granted with an eva...", issue_category: nil, decision_date: nil, disposition: "DTA Error - PMRs", end_product_establishment_id: 167, removed_at: nil, rating_issue_associated_at: "2018-10-09 20:07:09", parent_request_issue_id: nil, notes: nil>]>
```

worked!
