### ISSUE TITLE
RemoveContention 404's in prod

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#7177]
I tried running `VBMSService.remove_contention!` in prod today, and it was returning a 404.

I'm not sure if that's because it's not deployed or if envoy is messing up or what.

When this is working we need to fix the contentions on RampRefiling (id: 627) in prod that were created as a result of https://github.com/department-of-veterans-affairs/caseflow/issues/7176

steps to reproduce

```
> rr = RampRefiling.find 627
> contentions = rr.end_product_establishment.contentions
> VBMSService.remove_contention!(contentions.last)
```

**Comment by shanear** [comment]
Asking #appeals-devops to see if its an envoy issue.

**Comment by lisac-usds** [comment]
I'll take a look from the envoy / forward proxy angle and report back tonight.

**Comment by lisac-usds** [comment]
I'm sorry, wasn't able to take care of this today. Will revisit tomorrow.

**Comment by lisac-usds** [comment]
hi @pkarman @shanear , could you give me a RampRefiling ID that works in the UAT or Prepared environments? I think it might help me to track what happens in the non-404 cases, to help debug the 404 case in prod. Thanks!

**Comment by shanear** [comment]
@lisac-usds 

```
EndProductEstablishment.last.contentions.first
```

should get get you a contention to pass into `VBMSService.remove_contention!(contention)`

see:
<img width="1424" alt="screen shot 2018-10-03 at 2 55 32 pm" src="https://user-images.githubusercontent.com/1596259/46432490-6908db80-c71c-11e8-82ba-e953c370cf14.png">

**Comment by lisac-usds** [comment]
@shanear @pkarman is it noteworthy that `FeatureToggle.enabled?(:claims_service_v5)` is`true` in UAT (where we don't get a 404), whereas it's `false` in prod?

I noticed that discrepancy when tracking through the 404 stack trace on prod -
```
dependencies.rb:292:in `require'
bin/rails:4:in `<main>'
Traceback (most recent call last):
        6: from (irb):6
        5: from app/services/external_api/vbms_service.rb:141:in `remove_contention!'
        4: from app/services/external_api/vbms_service.rb:188:in `send_and_log_request'
        3: from app/services/metrics_service.rb:12:in `record'
        2: from app/services/metrics_service.rb:13:in `block in record'
        1: from app/services/external_api/vbms_service.rb:191:in `block in send_and_log_request'
VBMS::HTTPError (status_code=404, body=, request=#<VBMS::Requests::RemoveContention:....
```
Looking at `remove_contention!` [L133](https://github.com/department-of-veterans-affairs/caseflow/blob/bb0a2a879b8817d805e4f886b7a131901a174b73/app/services/external_api/vbms_service.rb#L133), I see that particular feature toggle comes into play.  

So I was thinking, to debug further, one of these:
- on UAT, change the toggle to `false` and see if the 404 comes up there
- on prod, change the toggle to `true` and see if the 404 still comes up
- on prod, alter L137 so that `v5: FeatureToggle.enabled?(:claims_service_v5)` --> `v5: true` , and see if the 404 still comes up (limit the scope of the toggle)

(would be doing these on a detached instance, ie not in rotation)


I think I'll proceed with the attempt on UAT later today, but just wanted to keep you posted. Thanks!

**Comment by pkarman** [comment]
@lisac-usds it is noteworthy (I had noticed the same thing). I believe that we are not ready to use v5 in prod though, so toggling in UAT would be the most telling.

**Comment by lisac-usds** [comment]
thanks @pkarman. I ran into a hurdle testing this on UAT. Can you help me some more with this approach?
What it looks like to me: there are no more contentions available on which to try the `remove_contention!` -

```
# disable the toggle, for the scope of this test
irb(main):011:0> FeatureToggle.disable!(:claims_service_v5)
=> true
irb(main):012:0> FeatureToggle.enabled?(:claims_service_v5)
=> false
# try a remove_contention
irb(main):013:0> VBMSService.remove_contention!(EndProductEstablishment.last.contentions.first)
[...]
Traceback (most recent call last):
        2: from (irb):13
        1: from app/services/external_api/vbms_service.rb:141:in `remove_contention!'
NoMethodError (undefined method `claim_id' for nil:NilClass)

# try another remove_contention
irb(main):014:0> VBMSService.remove_contention!(EndProductEstablishment.first.contentions.first)
[...]
Traceback (most recent call last):
        2: from (irb):14
        1: from app/services/external_api/vbms_service.rb:141:in `remove_contention!'
NoMethodError (undefined method `claim_id' for nil:NilClass)

# re-enable the toggle
irb(main):015:0> FeatureToggle.enable!(:claims_service_v5)
=> true
irb(main):016:0> FeatureToggle.enabled?(:claims_service_v5)
=> true
irb(main):017:0> 
```

Is it an option to add a contention to UAT, so that we can try this call with the `:claims_service_v5` disabled? I'm out of my depth with how to add a contention.

**Comment by lisac-usds** [comment]
hey @pkarman , would you have time to pair on this tomorrow after 4pm ET? I'm getting an issue with the `request_issues` - it's a private method, something like that? - and fumbling in general. 

I'm losing confidence that the 404s in prod tie back to a setting in the forward proxy, as that configuration is pretty consistent across environments. Other things on my mind: perhaps a certificate on our end, or the feature toggle; or possibly something on the VBMS side? Sorry not to have an answer today. :/

**Comment by pkarman** [comment]
v4 and v5 work in UAT:

```
irb(main):001:0> FeatureToggle.enabled?(:claims_service_v5)
=> true
irb(main):002:0> FeatureToggle.disable!(:claims_service_v5)
=> true
irb(main):003:0> FeatureToggle.enabled?(:claims_service_v5)
=> false
irb(main):004:0> VBMSService.remove_contention!(EndProductEstablishment.last.contentions.first)
[2018-10-04 12:00:55 -0400]   EndProductEstablishment Load (0.8ms)  SELECT  "end_product_establishments".* FROM "end_product_establishments" ORDER BY "end_product_establishments"."id" DESC LIMIT $1  [["LIMIT", 1]]
[2018-10-04 12:00:55 -0400] STARTED sent VBMS request VBMS::Requests::ListContentions for 600139376
[2018-10-04 12:00:57 -0400] FINISHED sent VBMS request VBMS::Requests::ListContentions for 600139376:   0.017638   0.004181   0.021819 (  1.921906)

[2018-10-04 12:00:57 -0400] STARTED sent VBMS request VBMS::Requests::RemoveContention for 600139376
[2018-10-04 12:00:59 -0400] FINISHED sent VBMS request VBMS::Requests::RemoveContention for 600139376:   0.017687   0.000163   0.017850 (  1.888377)

=> "true"
irb(main):005:0> EndProductEstablishment.last.contentions
[2018-10-04 12:01:20 -0400]   EndProductEstablishment Load (0.8ms)  SELECT  "end_product_establishments".* FROM "end_product_establishments" ORDER BY "end_product_establishments"."id" DESC LIMIT $1  [["LIMIT", 1]]
[2018-10-04 12:01:20 -0400] STARTED sent VBMS request VBMS::Requests::ListContentions for 600139376
[2018-10-04 12:01:21 -0400] FINISHED sent VBMS request VBMS::Requests::ListContentions for 600139376:   0.016528   0.000000   0.016528 (  0.985816)

=> []
irb(main):006:0> epe = EndProductEstablishment.last
[2018-10-04 12:01:49 -0400]   EndProductEstablishment Load (0.9ms)  SELECT  "end_product_establishments".* FROM "end_product_establishments" ORDER BY "end_product_establishments"."id" DESC LIMIT $1  [["LIMIT", 1]]
=> #<EndProductEstablishment id: 139, established_at: "2018-10-04 14:44:30", synced_status: "PEND", source_type: "SupplementalClaim", source_id: 65, veteran_file_number: "700032044", reference_id: "600139376", claim_date: "2018-09-20", code: "040SCNR", modifier: "040", station: "397", last_synced_at: "2018-10-04 16:00:06", claimant_participant_id: "600231201", payee_code: "00", committed_at: "2018-10-04 14:44:32", doc_reference_id: nil, development_item_reference_id: nil, benefit_type_code: "1">
irb(main):007:0> epe.source.request_issues.each { |ri| ri.update!(contention_reference_id: nil) }
[2018-10-04 12:02:08 -0400]   SupplementalClaim Load (0.8ms)  SELECT  "supplemental_claims".* FROM "supplemental_claims" WHERE "supplemental_claims"."id" = $1 LIMIT $2  [["id", 65], ["LIMIT", 1]]
[2018-10-04 12:02:08 -0400]   RequestIssue Load (0.8ms)  SELECT "request_issues".* FROM "request_issues" WHERE "request_issues"."review_request_id" = $1 AND "request_issues"."review_request_type" = $2  [["review_request_id", 65], ["review_request_type", "SupplementalClaim"]]
[2018-10-04 12:02:08 -0400]    (1.3ms)  BEGIN
[2018-10-04 12:02:08 -0400]   SQL (0.7ms)  UPDATE "request_issues" SET "contention_reference_id" = $1 WHERE "request_issues"."id" = $2  [["contention_reference_id", nil], ["id", 274]]
[2018-10-04 12:02:08 -0400]    (2.1ms)  COMMIT
=> [#<RequestIssue id: 274, review_request_type: "SupplementalClaim", review_request_id: 65, rating_issue_reference_id: nil, rating_issue_profile_date: nil, contention_reference_id: nil, description: "test", issue_category: "Apportionment", decision_date: "2018-10-04", disposition: nil, end_product_establishment_id: 139, removed_at: nil, rating_issue_associated_at: nil, parent_request_issue_id: nil>]
irb(main):008:0> epe.contentions
[2018-10-04 12:02:17 -0400] STARTED sent VBMS request VBMS::Requests::ListContentions for 600139376
[2018-10-04 12:02:19 -0400] FINISHED sent VBMS request VBMS::Requests::ListContentions for 600139376:   0.020828   0.004532   0.025360 (  1.762109)

=> []
irb(main):009:0> epe.create_contentions!
[2018-10-04 12:02:24 -0400]   EndProductEstablishment Load (0.8ms)  SELECT  "end_product_establishments".* FROM "end_product_establishments" WHERE "end_product_establishments"."id" = $1 LIMIT $2  [["id", 139], ["LIMIT", 1]]
[2018-10-04 12:02:24 -0400]   EndProductEstablishment Load (0.6ms)  SELECT "end_product_establishments".* FROM "end_product_establishments" WHERE "end_product_establishments"."source_id" = $1 AND "end_product_establishments"."source_type" = $2  [["source_id", 65], ["source_type", "SupplementalClaim"]]
[2018-10-04 12:02:24 -0400] STARTED sent VBMS request VBMS::Requests::CreateContentions for 600139376
[2018-10-04 12:02:26 -0400] FINISHED sent VBMS request VBMS::Requests::CreateContentions for 600139376:   0.019079   0.000265   0.019344 (  2.040545)

[2018-10-04 12:02:26 -0400]    (0.6ms)  BEGIN
[2018-10-04 12:02:26 -0400]   SQL (0.8ms)  UPDATE "request_issues" SET "contention_reference_id" = $1 WHERE "request_issues"."id" = $2  [["contention_reference_id", "307202"], ["id", 274]]
[2018-10-04 12:02:26 -0400]    (1.4ms)  COMMIT
=> nil
irb(main):010:0> epe.contentions
=> []
irb(main):011:0> epe.reload
[2018-10-04 12:02:39 -0400]   EndProductEstablishment Load (0.9ms)  SELECT  "end_product_establishments".* FROM "end_product_establishments" WHERE "end_product_establishments"."id" = $1 LIMIT $2  [["id", 139], ["LIMIT", 1]]
=> #<EndProductEstablishment id: 139, established_at: "2018-10-04 14:44:30", synced_status: "PEND", source_type: "SupplementalClaim", source_id: 65, veteran_file_number: "700032044", reference_id: "600139376", claim_date: "2018-09-20", code: "040SCNR", modifier: "040", station: "397", last_synced_at: "2018-10-04 16:02:07", claimant_participant_id: "600231201", payee_code: "00", committed_at: "2018-10-04 14:44:32", doc_reference_id: nil, development_item_reference_id: nil, benefit_type_code: "1">
irb(main):012:0> epe.contentions
=> []
irb(main):013:0> epe = EndProductEstablishment.last
[2018-10-04 12:03:01 -0400]   EndProductEstablishment Load (1.0ms)  SELECT  "end_product_establishments".* FROM "end_product_establishments" ORDER BY "end_product_establishments"."id" DESC LIMIT $1  [["LIMIT", 1]]
=> #<EndProductEstablishment id: 139, established_at: "2018-10-04 14:44:30", synced_status: "PEND", source_type: "SupplementalClaim", source_id: 65, veteran_file_number: "700032044", reference_id: "600139376", claim_date: "2018-09-20", code: "040SCNR", modifier: "040", station: "397", last_synced_at: "2018-10-04 16:02:07", claimant_participant_id: "600231201", payee_code: "00", committed_at: "2018-10-04 14:44:32", doc_reference_id: nil, development_item_reference_id: nil, benefit_type_code: "1">
irb(main):014:0> epe.contentions
[2018-10-04 12:03:03 -0400] STARTED sent VBMS request VBMS::Requests::ListContentions for 600139376
[2018-10-04 12:03:05 -0400] FINISHED sent VBMS request VBMS::Requests::ListContentions for 600139376:   0.017038   0.000000   0.017038 (  1.066658)

=> [#<VBMS::Responses::Contention id="307202", text="test", start_date=Thu, 04 Oct 2018, submit_date=Thu, 04 Oct 2018, actionable_item="false", awaiting_response="unknown", claim_id="600139376", classification_cd=nil, contention_category=nil, file_number="700032044", level_status_code=nil, medical="false", participant_contention="unknown", secondary_to_contention_id="1068", type_code="NEW", working_contention="unknown">]
irb(main):015:0> FeatureToggle.enable!(:claims_service_v5)
=> true
irb(main):016:0> FeatureToggle.enabled?(:claims_service_v5)
=> true
irb(main):017:0> VBMSService.remove_contention!(EndProductEstablishment.last.contentions.first)
[2018-10-04 12:03:45 -0400]   EndProductEstablishment Load (0.9ms)  SELECT  "end_product_establishments".* FROM "end_product_establishments" ORDER BY "end_product_establishments"."id" DESC LIMIT $1  [["LIMIT", 1]]
[2018-10-04 12:03:45 -0400] STARTED sent VBMS request VBMS::Requests::ListContentions for 600139376
[2018-10-04 12:03:46 -0400] FINISHED sent VBMS request VBMS::Requests::ListContentions for 600139376:   0.018516   0.000000   0.018516 (  1.113932)

[2018-10-04 12:03:46 -0400] STARTED sent VBMS request VBMS::Requests::RemoveContention for 600139376
[2018-10-04 12:03:48 -0400] FINISHED sent VBMS request VBMS::Requests::RemoveContention for 600139376:   0.018097   0.000000   0.018097 (  2.088727)

=> "true"
irb(main):018:0> epe = EndProductEstablishment.last
[2018-10-04 12:04:22 -0400]   EndProductEstablishment Load (1.1ms)  SELECT  "end_product_establishments".* FROM "end_product_establishments" ORDER BY "end_product_establishments"."id" DESC LIMIT $1  [["LIMIT", 1]]
=> #<EndProductEstablishment id: 139, established_at: "2018-10-04 14:44:30", synced_status: "PEND", source_type: "SupplementalClaim", source_id: 65, veteran_file_number: "700032044", reference_id: "600139376", claim_date: "2018-09-20", code: "040SCNR", modifier: "040", station: "397", last_synced_at: "2018-10-04 16:02:07", claimant_participant_id: "600231201", payee_code: "00", committed_at: "2018-10-04 14:44:32", doc_reference_id: nil, development_item_reference_id: nil, benefit_type_code: "1">
irb(main):019:0> epe.contentions
[2018-10-04 12:04:25 -0400] STARTED sent VBMS request VBMS::Requests::ListContentions for 600139376
[2018-10-04 12:04:26 -0400] FINISHED sent VBMS request VBMS::Requests::ListContentions for 600139376:   0.016635   0.000000   0.016635 (  1.024016)

=> []
```

**Comment by lisac-usds** [comment]
ooh, this is very interesting, @leikkisa ! I'd love for this to be a permissions / BGS-side thing. I'm stumped about what else to try on our end - it's unlikely to do with the value of `FeatureToggle.enabled?(:claims_service_v5)`, seeing Peter's debugging earlier today; and the only other thing I can think of that could come into play would be certificates, but... very odd that it would manifest in this behavior.

Do you know whether anyone's already reached out to VBMS about the BGS informal conference request in prod? Is this something I should do?

**Comment by leikkisa** [comment]
@lisac-usds We just had a meeting with them today which is why I posted the above comment. So it's on the radar, but we should follow up with VBMS next

**Comment by pkarman** [comment]
turns out the difference in UAT and prod is that UAT is not using the forward proxy.

in uat
```irb(main):001:0> FeatureToggle.enabled?(:vbms_forward_proxy)
=> false
```
but in prod
```irb(main):001:0> FeatureToggle.enabled?(:vbms_forward_proxy)
=> true
```

**Comment by shanear** [comment]
> We are having a similar issue with informal conference request in prod (which we go through BGS for). BGS said that one might be due to a permissions issue, or maybe it's because the endpoint needs to be turned on in prod.

Yeah, BGS has to deploy individual services in prod. That's what the WSCR is for 🙂
https://github.com/department-of-veterans-affairs/caseflow/issues/7199

**Comment by leikkisa** [comment]
Ah, okay. So if we add a new service to connect_vbms, we should also add it to "appeals-deployment/ansible/vars/va-services.yml".  Very good to know.

**Comment by pkarman** [comment]
Confirmed in UAT that enabling the forward proxy with the new envoy config works as expected:

```
irb(main):001:0> FeatureToggle.enabled?(:vbms_forward_proxy)
=> false
irb(main):002:0> FeatureToggle.enable!(:vbms_forward_proxy)
=> true
irb(main):003:0> FeatureToggle.enabled?(:vbms_forward_proxy)
=> true
irb(main):004:0> VBMSService.remove_contention!(EndProductEstablishment.last.contentions.first)
[2018-10-09 10:55:24 -0400]   EndProductEstablishment Load (1.2ms)  SELECT  "end_product_establishments".* FROM "end_product_establishments" ORDER BY "end_product_establishments"."id" DESC LIMIT $1  [["LIMIT", 1]]
[2018-10-09 10:55:24 -0400] STARTED sent VBMS request VBMS::Requests::ListContentions for 600140077
[2018-10-09 10:55:27 -0400] FINISHED sent VBMS request VBMS::Requests::ListContentions for 600140077:   0.014193   0.004236   0.018429 (  2.369908)

[2018-10-09 10:55:27 -0400] STARTED sent VBMS request VBMS::Requests::RemoveContention for 600140077
[2018-10-09 10:55:30 -0400] FINISHED sent VBMS request VBMS::Requests::RemoveContention for 600140077:   0.010612   0.003814   0.014426 (  3.481745)

=> "true"
irb(main):005:0>
```

**Comment by shanear** [comment]
I think we needed to keep the original 2 around.
