### ISSUE TITLE
Flakey test: `Search queue case search for appeals using veteran id when backend encounters an error searching in search bar produces another error`

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#7650]
spec.feature.queue.search_spec spec/feature/queue/search_spec.rb

Failure/Error: let(:veteran_with_no_appeals) { FactoryBot.create(:veteran) }
```
ActiveRecord::RecordNotUnique:
  PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_veterans_on_file_number"
  DETAIL:  Key (file_number)=(100000021) already exists.
  : INSERT INTO "veterans" ("file_number", "participant_id", "first_name", "last_name", "name_suffix") VALUES ($1, $2, $3, $4, $5) RETURNING "id"
./spec/feature/queue/search_spec.rb:9:in `block (2 levels) in <top (required)>'
./spec/feature/queue/search_spec.rb:88:in `block (4 levels) in <top (required)>'
------------------
--- Caused by: ---
PG::UniqueViolation:
  ERROR:  duplicate key value violates unique constraint "index_veterans_on_file_number"
  DETAIL:  Key (file_number)=(100000021) already exists.
  ./spec/feature/queue/search_spec.rb:9:in `block (2 levels) in <top (required)>'
```
https://circleci.com/gh/department-of-veterans-affairs/caseflow/18680

**Comment by mdbenjam** [comment]
Another case: https://circleci.com/gh/department-of-veterans-affairs/caseflow/20196
