### ISSUE TITLE
Flakey edit issues & add issues tests

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#8341]
https://circleci.com/gh/department-of-veterans-affairs/caseflow/27546#tests/containers/0

```
Edit issues Higher-Level Reviews when there is a rating end product has decision issues shows decision isssues and allows adding/removing issues - spec.feature.intake.edit_spec
spec/feature/intake/edit_spec.rb
Failure/Error:
  expect(page).to have_content(
    Constants.INELIGIBLE_REQUEST_ISSUES
      .duplicate_of_issue_in_active_review.gsub("{review_title}", "Higher-Level Review")
  )

  expected to find text "is ineligible because it's already under review as a Higher-Level Review" in "Caseflow> Intake | Merica, Ed (100000014) DSUSER (DSUSER) Add / Remove Issues Form Decision Review Request: Higher-Level Review — VA Form 20-0996 Veteran Ed Merica (100000014) Receipt date of this form 05/05/2018 Benefit type Compensation Informal conference request No Same office request No Claimant Bob Vance, Spouse (payee code 10) Requested issues 1. PTSD denied Decision date: 11/02/2017 Remove 2. rating decision issue Decision date: 05/23/2018 Remove 3. nonrating decision issue dispositon: Active Duty Adjustments - Test nonrating decision issue Decision date: 05/21/2018 Remove + Add issue Cancel editSave 3 issues Built with ♡ by theDigital Service at VA Track Caseflow Status|Send feedback"
./spec/feature/intake/edit_spec.rb:296:in `verify_decision_issues_can_be_added_and_removed'
./spec/feature/intake/edit_spec.rb:814:in `block (5 levels) in <top (required)>'
Edit issues Supplemental claims when there is a rating end product has decision issues shows decision isssues and allows adding/removing issues - spec.feature.intake.edit_spec
spec/feature/intake/edit_spec.rb
Failure/Error:
  expect(page).to have_content(
    Constants.INELIGIBLE_REQUEST_ISSUES
      .duplicate_of_issue_in_active_review.gsub("{review_title}", "Higher-Level Review")
  )

  expected to find text "is ineligible because it's already under review as a Higher-Level Review" in "Caseflow> Intake | Merica, Ed (100000025) DSUSER (DSUSER) Add / Remove Issues Form Decision Review Request: Supplemental Claim — VA Form 20-0995 Veteran Ed Merica (100000025) Receipt date of this form 05/05/2018 Benefit type Compensation Claimant Bob Vance, Spouse (payee code 10) Requested issues 1. PTSD denied Decision date: 11/02/2017 Remove 2. rating decision issue Decision date: 05/23/2018 Remove 3. nonrating decision issue dispositon: Active Duty Adjustments - Test nonrating decision issue Decision date: 05/21/2018 Remove + Add issue Cancel editSave 3 issues Built with ♡ by theDigital Service at VA Track Caseflow Status|Send feedback"
./spec/feature/intake/edit_spec.rb:296:in `verify_decision_issues_can_be_added_and_removed'
./spec/feature/intake/edit_spec.rb:1354:in `block (5 levels) in <top (required)>'
```

**Comment by mdbenjam** [comment]
Looks like this might already be fixed!
