### ISSUE TITLE
Flakey checkout_flows_spec test

### ISSUE THREAD

**Issue by monfresh** [department-of-veterans-affairs/caseflow#8399]
``` 
1.1) Failure/Error: dropdown = container.find(".Select-control")

          Capybara::ElementNotFound:
            Unable to find visible css ".Select-control"
          # ./spec/support/feature_helper.rb:4:in `click_dropdown'
          # ./spec/feature/queue/checkout_flows_spec.rb:841:in `block (3 levels) in <top (required)>
```
https://circleci.com/gh/department-of-veterans-affairs/caseflow/28750#tests/containers/1

**Comment by aroltsch** [comment]
Have we seen this again? @monfresh

**Comment by monfresh** [comment]
Not that I recall.

**Comment by aroltsch** [comment]
We will close it for now.
