### ISSUE TITLE
Flakey hearing schedule_veteran_spec

### ISSUE THREAD

**Issue by monfresh** [department-of-veterans-affairs/caseflow#8949]
```Failure/Error: container.find(".Select-control")

Capybara::ElementNotFound:
  Unable to find visible css ".Select-control"
./spec/support/feature_helper.rb:7:in `click_dropdown'
./spec/feature/hearing_schedule/schedule_veteran_spec.rb:130:in `block (4 levels) in <top (required)>'
./spec/feature/hearing_schedule/schedule_veteran_spec.rb:122:in `block (3 levels) in <top (required)>'
```
https://circleci.com/gh/department-of-veterans-affairs/caseflow/36276

**Comment by mdbenjam** [comment]
I think this is fixed by this: https://github.com/department-of-veterans-affairs/caseflow/pull/9014/files#diff-79267524a3da312020611492685b5df4L9

Ran the test 20 times on CI and got zero failures, so 🤞
