### ISSUE TITLE
Flakey test in RequestIssue spec

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#9192]
https://circleci.com/gh/department-of-veterans-affairs/caseflow/39595?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
RequestIssue#validate_eligibility! issues with previous decision reviews when the previous review is an appeal when the current review is a higher level review is not eligible after an appeal - spec.models.request_issue_spec
spec/models/request_issue_spec.rb
Failure/Error: expect(rating_request_issue.ineligible_reason).to eq("appeal_to_higher_level_review")

  expected: "appeal_to_higher_level_review"
       got: "higher_level_review_to_higher_level_review"

  (compared using ==)
./spec/models/request_issue_spec.rb:768:in `block (6 levels) in <top (required)>'
RequestIssue#validate_eligibility! issues with previous decision reviews when the previous review is an appeal when the current review is an appeal is not eligible after an appeal - spec.models.request_issue_spec
spec/models/request_issue_spec.rb
Failure/Error: expect(rating_request_issue.ineligible_due_to).to eq(previous_request_issue)

  expected: #<RequestIssue id: 171, benefit_type: "compensation", contention_reference_id: 1234, contested_decisi...untimely_exemption_notes: nil, vacols_id: nil, vacols_sequence_id: nil, veteran_participant_id: nil>
       got: #<RequestIssue id: 168, benefit_type: "compensation", contention_reference_id: 1234, contested_decisi...untimely_exemption_notes: nil, vacols_id: nil, vacols_sequence_id: nil, veteran_participant_id: nil>

  (compared using ==)

  Diff:



  @@ -1,16 +1,16 @@
  -#<RequestIssue:0x000055f106a67280
  - id: 171,
  +#<RequestIssue:0x000055f108507108
  + id: 168,
    benefit_type: "compensation",
    contention_reference_id: 1234,
    contested_decision_issue_id: nil,
  - contested_issue_description: nil,
  + contested_issue_description: "a rating request issue",
    contested_rating_issue_diagnostic_code: "5008",
    contested_rating_issue_disability_code: nil,
  - contested_rating_issue_profile_date: nil,
  + contested_rating_issue_profile_date: "2018-01-01 12:00:00 UTC",
    contested_rating_issue_reference_id: "hlr123",
    created_at: Mon, 01 Jan 2018 12:00:00 UTC +00:00,
    decision_date: nil,
  - decision_review_id: 9,
  + decision_review_id: 8,
    decision_review_type: "Appeal",
    decision_sync_attempted_at: nil,
    decision_sync_error: nil,
  @@ -32,7 +32,7 @@
    rating_issue_profile_date: nil,
    rating_issue_reference_id: nil,
    removed_at: nil,
  - review_request_id: 9,
  + review_request_id: 8,
    review_request_type: "Appeal",
    unidentified_issue_text: nil,
    untimely_exemption: nil,
./spec/models/request_issue_spec.rb:786:in `block (6 levels) in <top (required)>'
```

Only seen once so far.

**Comment by laurjpeterson** [comment]
Closing. Tracking in flakey test running ticket here https://github.com/department-of-veterans-affairs/caseflow/issues/10516
