### ISSUE TITLE
Error not properly getting saved when RequestIssue decision sync fails

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#9212]
The 404 error for syncing dispositions has been causing a RequestIssue in prod to fail. However, there is no error saved in `decision_sync_error`

**Comment by shanear** [comment]
```
[2019-02-05 13:21:31 -0500] STARTED sent VBMS request VBMS::Requests::GetDispositions for 70244484
[2019-02-05 13:21:31 -0500] VBMS HTTP Error 404 (GetDispositions) 
[2019-02-05 13:21:31 -0500] status_code=404, body=, request=#<VBMS::Requests::GetDispositions:0x0000556dadccc9a8 @claim_id="70244484">
/opt/caseflow-certification/src/vendor/bundle/ruby/2.5.0/bundler/gems/connect_vbms-0d56a6c6a2ec/lib/vbms/client.rb:102:in `send_request'
/opt/caseflow-certification/src/app/services/external_api/vbms_service.rb:205:in `block in send_and_log_request'
/opt/caseflow-certification/src/app/services/metrics_service.rb:13:in `block in record'
/opt/rbenv/versions/2.5.1/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
/opt/caseflow-certification/src/app/services/metrics_service.rb:12:in `record'
/opt/caseflow-certification/src/app/services/external_api/vbms_service.rb:202:in `send_and_log_request'
/opt/caseflow-certification/src/app/services/external_api/vbms_service.rb:177:in `get_dispositions!'
/opt/caseflow-certification/src/app/models/end_product_establishment.rb:174:in `fetch_dispositions_from_vbms'
/opt/caseflow-certification/src/app/models/request_issue.rb:457:in `contention_disposition'
/opt/caseflow-certification/src/app/models/request_issue.rb:442:in `create_decision_issue_from_disposition'
/opt/caseflow-certification/src/app/models/request_issue.rb:428:in `create_decision_issues'
/opt/caseflow-certification/src/app/models/request_issue.rb:329:in `block in sync_decision_issues!'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/opt/rbenv/versions/2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6.1/lib/active_record/transactions.rb:210:in `transaction'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.6.1/lib/active_record/transactions.rb:299:in `transaction'
/opt/caseflow-certification/src/app/models/request_issue.rb:328:in `sync_decision_issues!'
(irb):29:in `irb_binding'
/opt/rbenv/versions/2.5.1/lib/ruby/2.5.0/irb/workspace.rb:85:in `eval'
/opt/rbenv/versions/2.5.1/lib/ruby/2.5.0/irb/workspace.rb:85:in `evaluate'
/opt/rbenv/versions/2.5.1/lib/ruby/2.5.0/irb/context.rb:380:in `evaluate'
/opt/rbenv/versions/2.5.1/lib/ruby/2.5.0/irb.rb:491:in `block (2 levels) in eval_input'
/opt/rbenv/versions/2.5.1/lib/ruby/2.5.0/irb.rb:623:in `signal_status'
/opt/rbenv/versions/2.5.1/lib/ruby/2.5.0/irb.rb:488:in `block in eval_input'
/opt/rbenv/versions/2.5.1/lib/ruby/2.5.0/irb/ruby-lex.rb:246:in `block (2 levels) in each_top_level_statement'
/opt/rbenv/versions/2.5.1/lib/ruby/2.5.0/irb/ruby-lex.rb:232:in `loop'
/opt/rbenv/versions/2.5.1/lib/ruby/2.5.0/irb/ruby-lex.rb:232:in `block in each_top_level_statement'
/opt/rbenv/versions/2.5.1/lib/ruby/2.5.0/irb/ruby-lex.rb:231:in `catch'
/opt/rbenv/versions/2.5.1/lib/ruby/2.5.0/irb/ruby-lex.rb:231:in `each_top_level_statement'
/opt/rbenv/versions/2.5.1/lib/ruby/2.5.0/irb.rb:487:in `eval_input'
/opt/rbenv/versions/2.5.1/lib/ruby/2.5.0/irb.rb:428:in `block in run'
/opt/rbenv/versions/2.5.1/lib/ruby/2.5.0/irb.rb:427:in `catch'
/opt/rbenv/versions/2.5.1/lib/ruby/2.5.0/irb.rb:427:in `run'
/opt/rbenv/versions/2.5.1/lib/ruby/2.5.0/irb.rb:383:in `start'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.1/lib/rails/commands/console/console_command.rb:62:in `start'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.1/lib/rails/commands/console/console_command.rb:17:in `start'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.1/lib/rails/commands/console/console_command.rb:97:in `perform'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.1/lib/rails/command/base.rb:63:in `perform'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.1/lib/rails/command.rb:44:in `invoke'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.1/lib/rails/commands.rb:16:in `<main>'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/dependencies.rb:292:in `block in require'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/dependencies.rb:258:in `load_dependency'
/opt/caseflow-certification/src/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/dependencies.rb:292:in `require'
bin/rails:4:in `<main>'
[2019-02-05 13:21:31 -0500]    (0.8ms)  ROLLBACK
Traceback (most recent call last):
       12: from (irb):29
       11: from app/models/request_issue.rb:328:in `sync_decision_issues!'
       10: from app/models/request_issue.rb:329:in `block in sync_decision_issues!'
        9: from app/models/request_issue.rb:428:in `create_decision_issues'
        8: from app/models/request_issue.rb:442:in `create_decision_issue_from_disposition'
        7: from app/models/request_issue.rb:457:in `contention_disposition'
        6: from app/models/end_product_establishment.rb:174:in `fetch_dispositions_from_vbms'
        5: from app/services/external_api/vbms_service.rb:177:in `get_dispositions!'
        4: from app/services/external_api/vbms_service.rb:202:in `send_and_log_request'
        3: from app/services/metrics_service.rb:12:in `record'
        2: from app/services/metrics_service.rb:13:in `block in record'
        1: from app/services/external_api/vbms_service.rb:205:in `block in send_and_log_request'
```
