### ISSUE TITLE
Reseed the database to ensure migrations do not break deployments

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#933]
In relation to [pull #931](https://github.com/department-of-veterans-affairs/caseflow/pull/931)

The tasks were updated with a new state, but because the database is not reseeded in the tests - deployments exploded with errors:
```
"stderr": "caseflow_certification already exists\nrake aborted!\nAASM::InvalidTransition: Event 'complete' cannot transition from 'started'. \n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/aasm-4.11.1/lib/aasm/aasm.rb:191:in `aasm_failed'
\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/aasm-4.11.1/lib/aasm/aasm.rb:125:in `aasm_fire_event'
\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/aasm-4.11.1/lib/aasm/persistence/active_record_persistence.rb:194:in `block in aasm_fire_event'
\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213
```

Probably should have a `before(:all)` reseed of the database to catch errors like these.

**Comment by kierachell** [comment]
Tests work now.
