### ISSUE TITLE
Review Decision | VBMS::ClientError in `fetch_document_file`

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#951]
When attempting to establish a claim for a Remand
I am unable to see the documents:
![pdfjserr](https://cloud.githubusercontent.com/assets/18075411/23049343/66785e5c-f489-11e6-981e-4bb61285e231.png)
![pdfjserr2](https://cloud.githubusercontent.com/assets/18075411/23049344/66861aa6-f489-11e6-9684-72528b314e0b.png)
See backtrace below:
```
NoMethodError: undefined method `document_id' for #<Document:0x007f75fc1743e0>
  from active_model/attribute_methods.rb:433:in `method_missing'
  from app/services/appeal_repository.rb:276:in `fetch_document_file'
  from app/models/document.rb:50:in `fetch_and_cache_document_from_vbms'
  from app/models/document.rb:63:in `content'
  from app/models/document.rb:67:in `serve'
  from app/controllers/tasks_controller.rb:42:in `pdf'
  from action_controller/metal/implicit_render.rb:4:in `send_action'
  from abstract_controller/base.rb:198:in `process_action'
  from action_controller/metal/rendering.rb:10:in `process_action'
  from abstract_controller/callbacks.rb:20:in `block in process_action'
  from active_support/callbacks.rb:117:in `call'
  from active_support/callbacks.rb:117:in `call'
  from active_support/callbacks.rb:555:in `block (2 levels) in compile'
  from active_support/callbacks.rb:505:in `call'
  from active_support/callbacks.rb:505:in `call'
  from active_support/callbacks.rb:92:in `__run_callbacks__'
  from active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  from active_support/callbacks.rb:81:in `run_callbacks'
  from abstract_controller/callbacks.rb:19:in `process_action'
  from action_controller/metal/rescue.rb:29:in `process_action'
  from action_controller/metal/instrumentation.rb:32:in `block in process_action'
  from active_support/notifications.rb:164:in `block in instrument'
  from active_support/notifications/instrumenter.rb:20:in `instrument'
  from active_support/notifications.rb:164:in `instrument'
  from action_controller/metal/instrumentation.rb:30:in `process_action'
  from action_controller/metal/params_wrapper.rb:250:in `process_action'
  from active_record/railties/controller_runtime.rb:18:in `process_action'
  from abstract_controller/base.rb:137:in `process'
  from action_view/rendering.rb:30:in `process'
  from action_controller/metal.rb:196:in `dispatch'
  from action_controller/metal/rack_delegation.rb:13:in `dispatch'
  from action_controller/metal.rb:237:in `block in action'
  from action_dispatch/routing/route_set.rb:74:in `call'
  from action_dispatch/routing/route_set.rb:74:in `dispatch'
  from action_dispatch/routing/route_set.rb:43:in `serve'
  from action_dispatch/journey/router.rb:43:in `block in serve'
  from action_dispatch/journey/router.rb:30:in `each'
  from action_dispatch/journey/router.rb:30:in `serve'
  from action_dispatch/routing/route_set.rb:817:in `call'
  from rack/etag.rb:24:in `call'
  from rack/conditionalget.rb:25:in `call'
  from rack/head.rb:13:in `call'
  from action_dispatch/middleware/params_parser.rb:27:in `call'
  from action_dispatch/middleware/flash.rb:260:in `call'
  from rack/session/abstract/id.rb:225:in `context'
  from rack/session/abstract/id.rb:220:in `call'
  from action_dispatch/middleware/cookies.rb:560:in `call'
  from active_record/query_cache.rb:36:in `call'
  from active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  from action_dispatch/middleware/callbacks.rb:29:in `block in call'
  from active_support/callbacks.rb:88:in `__run_callbacks__'
  from active_support/callbacks.rb:778:in `_run_call_callbacks'
  from active_support/callbacks.rb:81:in `run_callbacks'
  from action_dispatch/middleware/callbacks.rb:27:in `call'
  from action_dispatch/middleware/remote_ip.rb:78:in `call'
  from action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  from action_dispatch/middleware/show_exceptions.rb:30:in `call'
  from rails/rack/logger.rb:38:in `call_app'
  from rails/rack/logger.rb:20:in `block in call'
  from active_support/tagged_logging.rb:68:in `block in tagged'
  from active_support/tagged_logging.rb:26:in `tagged'
  from active_support/tagged_logging.rb:68:in `tagged'
  from rails/rack/logger.rb:20:in `call'
  from request_store/middleware.rb:9:in `call'
  from action_dispatch/middleware/request_id.rb:21:in `call'
  from rack/methodoverride.rb:22:in `call'
  from rack/runtime.rb:18:in `call'
  from rack/timeout/core.rb:122:in `block in call'
  from rack/timeout/support/timeout.rb:19:in `call'
  from rack/timeout/support/timeout.rb:19:in `timeout'
  from rack/timeout/core.rb:121:in `call'
  from action_dispatch/middleware/static.rb:120:in `call'
  from rack/sendfile.rb:113:in `call'
  from raven/integrations/rack.rb:50:in `call'
  from action_dispatch/middleware/static.rb:120:in `call'
  from rails/engine.rb:518:in `call'
  from rails/application.rb:165:in `call'
  from prometheus/client/rack/exporter.rb:29:in `call'
  from prometheus/client/rack/collector.rb:24:in `block in call'
  from prometheus/client/rack/collector.rb:57:in `trace'
  from prometheus/client/rack/collector.rb:24:in `call'
  from rack/deflater.rb:35:in `call'
  from app/middleware/metrics_auth.rb:10:in `call'
  from puma/commonlogger.rb:31:in `call'
  from puma/configuration.rb:81:in `call'
  from puma/server.rb:557:in `handle_request'
  from puma/server.rb:404:in `process_client'
  from puma/server.rb:270:in `block in run'
  from puma/thread_pool.rb:106:in `call'
  from puma/thread_pool.rb:106:in `block in spawn_thread'
```
![backtrace](https://cloud.githubusercontent.com/assets/18075411/23049484/7118267a-f48a-11e6-8ecc-f4868a858961.png)

**Comment by shanear** [comment]
can you verify the PR fixed this issue?

**Comment by kierachell** [comment]
Yes fixed, this issue was never labeled properly so it just stayed in backlog.
